// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: state/v1/state.proto

package statev1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/terraconstructs/grid/pkg/api/state/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// StateServiceName is the fully-qualified name of the StateService service.
	StateServiceName = "state.v1.StateService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// StateServiceCreateStateProcedure is the fully-qualified name of the StateService's CreateState
	// RPC.
	StateServiceCreateStateProcedure = "/state.v1.StateService/CreateState"
	// StateServiceListStatesProcedure is the fully-qualified name of the StateService's ListStates RPC.
	StateServiceListStatesProcedure = "/state.v1.StateService/ListStates"
	// StateServiceGetStateConfigProcedure is the fully-qualified name of the StateService's
	// GetStateConfig RPC.
	StateServiceGetStateConfigProcedure = "/state.v1.StateService/GetStateConfig"
	// StateServiceGetStateLockProcedure is the fully-qualified name of the StateService's GetStateLock
	// RPC.
	StateServiceGetStateLockProcedure = "/state.v1.StateService/GetStateLock"
	// StateServiceUnlockStateProcedure is the fully-qualified name of the StateService's UnlockState
	// RPC.
	StateServiceUnlockStateProcedure = "/state.v1.StateService/UnlockState"
	// StateServiceAddDependencyProcedure is the fully-qualified name of the StateService's
	// AddDependency RPC.
	StateServiceAddDependencyProcedure = "/state.v1.StateService/AddDependency"
	// StateServiceRemoveDependencyProcedure is the fully-qualified name of the StateService's
	// RemoveDependency RPC.
	StateServiceRemoveDependencyProcedure = "/state.v1.StateService/RemoveDependency"
	// StateServiceListDependenciesProcedure is the fully-qualified name of the StateService's
	// ListDependencies RPC.
	StateServiceListDependenciesProcedure = "/state.v1.StateService/ListDependencies"
	// StateServiceListDependentsProcedure is the fully-qualified name of the StateService's
	// ListDependents RPC.
	StateServiceListDependentsProcedure = "/state.v1.StateService/ListDependents"
	// StateServiceSearchByOutputProcedure is the fully-qualified name of the StateService's
	// SearchByOutput RPC.
	StateServiceSearchByOutputProcedure = "/state.v1.StateService/SearchByOutput"
	// StateServiceGetTopologicalOrderProcedure is the fully-qualified name of the StateService's
	// GetTopologicalOrder RPC.
	StateServiceGetTopologicalOrderProcedure = "/state.v1.StateService/GetTopologicalOrder"
	// StateServiceGetStateStatusProcedure is the fully-qualified name of the StateService's
	// GetStateStatus RPC.
	StateServiceGetStateStatusProcedure = "/state.v1.StateService/GetStateStatus"
	// StateServiceGetDependencyGraphProcedure is the fully-qualified name of the StateService's
	// GetDependencyGraph RPC.
	StateServiceGetDependencyGraphProcedure = "/state.v1.StateService/GetDependencyGraph"
	// StateServiceListStateOutputsProcedure is the fully-qualified name of the StateService's
	// ListStateOutputs RPC.
	StateServiceListStateOutputsProcedure = "/state.v1.StateService/ListStateOutputs"
	// StateServiceGetStateInfoProcedure is the fully-qualified name of the StateService's GetStateInfo
	// RPC.
	StateServiceGetStateInfoProcedure = "/state.v1.StateService/GetStateInfo"
	// StateServiceListAllEdgesProcedure is the fully-qualified name of the StateService's ListAllEdges
	// RPC.
	StateServiceListAllEdgesProcedure = "/state.v1.StateService/ListAllEdges"
	// StateServiceUpdateStateLabelsProcedure is the fully-qualified name of the StateService's
	// UpdateStateLabels RPC.
	StateServiceUpdateStateLabelsProcedure = "/state.v1.StateService/UpdateStateLabels"
	// StateServiceGetLabelPolicyProcedure is the fully-qualified name of the StateService's
	// GetLabelPolicy RPC.
	StateServiceGetLabelPolicyProcedure = "/state.v1.StateService/GetLabelPolicy"
	// StateServiceSetLabelPolicyProcedure is the fully-qualified name of the StateService's
	// SetLabelPolicy RPC.
	StateServiceSetLabelPolicyProcedure = "/state.v1.StateService/SetLabelPolicy"
	// StateServiceCreateServiceAccountProcedure is the fully-qualified name of the StateService's
	// CreateServiceAccount RPC.
	StateServiceCreateServiceAccountProcedure = "/state.v1.StateService/CreateServiceAccount"
	// StateServiceListServiceAccountsProcedure is the fully-qualified name of the StateService's
	// ListServiceAccounts RPC.
	StateServiceListServiceAccountsProcedure = "/state.v1.StateService/ListServiceAccounts"
	// StateServiceRevokeServiceAccountProcedure is the fully-qualified name of the StateService's
	// RevokeServiceAccount RPC.
	StateServiceRevokeServiceAccountProcedure = "/state.v1.StateService/RevokeServiceAccount"
	// StateServiceRotateServiceAccountProcedure is the fully-qualified name of the StateService's
	// RotateServiceAccount RPC.
	StateServiceRotateServiceAccountProcedure = "/state.v1.StateService/RotateServiceAccount"
	// StateServiceCreateRoleProcedure is the fully-qualified name of the StateService's CreateRole RPC.
	StateServiceCreateRoleProcedure = "/state.v1.StateService/CreateRole"
	// StateServiceListRolesProcedure is the fully-qualified name of the StateService's ListRoles RPC.
	StateServiceListRolesProcedure = "/state.v1.StateService/ListRoles"
	// StateServiceUpdateRoleProcedure is the fully-qualified name of the StateService's UpdateRole RPC.
	StateServiceUpdateRoleProcedure = "/state.v1.StateService/UpdateRole"
	// StateServiceDeleteRoleProcedure is the fully-qualified name of the StateService's DeleteRole RPC.
	StateServiceDeleteRoleProcedure = "/state.v1.StateService/DeleteRole"
	// StateServiceAssignRoleProcedure is the fully-qualified name of the StateService's AssignRole RPC.
	StateServiceAssignRoleProcedure = "/state.v1.StateService/AssignRole"
	// StateServiceRemoveRoleProcedure is the fully-qualified name of the StateService's RemoveRole RPC.
	StateServiceRemoveRoleProcedure = "/state.v1.StateService/RemoveRole"
	// StateServiceListUserRolesProcedure is the fully-qualified name of the StateService's
	// ListUserRoles RPC.
	StateServiceListUserRolesProcedure = "/state.v1.StateService/ListUserRoles"
	// StateServiceAssignGroupRoleProcedure is the fully-qualified name of the StateService's
	// AssignGroupRole RPC.
	StateServiceAssignGroupRoleProcedure = "/state.v1.StateService/AssignGroupRole"
	// StateServiceRemoveGroupRoleProcedure is the fully-qualified name of the StateService's
	// RemoveGroupRole RPC.
	StateServiceRemoveGroupRoleProcedure = "/state.v1.StateService/RemoveGroupRole"
	// StateServiceListGroupRolesProcedure is the fully-qualified name of the StateService's
	// ListGroupRoles RPC.
	StateServiceListGroupRolesProcedure = "/state.v1.StateService/ListGroupRoles"
	// StateServiceGetEffectivePermissionsProcedure is the fully-qualified name of the StateService's
	// GetEffectivePermissions RPC.
	StateServiceGetEffectivePermissionsProcedure = "/state.v1.StateService/GetEffectivePermissions"
	// StateServiceListSessionsProcedure is the fully-qualified name of the StateService's ListSessions
	// RPC.
	StateServiceListSessionsProcedure = "/state.v1.StateService/ListSessions"
	// StateServiceRevokeSessionProcedure is the fully-qualified name of the StateService's
	// RevokeSession RPC.
	StateServiceRevokeSessionProcedure = "/state.v1.StateService/RevokeSession"
	// StateServiceSetOutputSchemaProcedure is the fully-qualified name of the StateService's
	// SetOutputSchema RPC.
	StateServiceSetOutputSchemaProcedure = "/state.v1.StateService/SetOutputSchema"
	// StateServiceGetOutputSchemaProcedure is the fully-qualified name of the StateService's
	// GetOutputSchema RPC.
	StateServiceGetOutputSchemaProcedure = "/state.v1.StateService/GetOutputSchema"
)

// StateServiceClient is a client for the state.v1.StateService service.
type StateServiceClient interface {
	// CreateState creates a new state with client-generated GUID and logic ID.
	CreateState(context.Context, *connect.Request[v1.CreateStateRequest]) (*connect.Response[v1.CreateStateResponse], error)
	// ListStates returns all states with summary information.
	ListStates(context.Context, *connect.Request[v1.ListStatesRequest]) (*connect.Response[v1.ListStatesResponse], error)
	// GetStateConfig retrieves backend configuration for an existing state by logic ID.
	GetStateConfig(context.Context, *connect.Request[v1.GetStateConfigRequest]) (*connect.Response[v1.GetStateConfigResponse], error)
	// GetStateLock inspects the current lock metadata for a state by GUID.
	GetStateLock(context.Context, *connect.Request[v1.GetStateLockRequest]) (*connect.Response[v1.GetStateLockResponse], error)
	// UnlockState releases a lock using the lock ID provided by Terraform/OpenTofu.
	UnlockState(context.Context, *connect.Request[v1.UnlockStateRequest]) (*connect.Response[v1.UnlockStateResponse], error)
	// AddDependency declares a dependency edge from producer output to consumer state.
	// Returns existing edge if duplicate (idempotent). Rejects if would create cycle.
	AddDependency(context.Context, *connect.Request[v1.AddDependencyRequest]) (*connect.Response[v1.AddDependencyResponse], error)
	// RemoveDependency deletes a dependency edge by ID.
	RemoveDependency(context.Context, *connect.Request[v1.RemoveDependencyRequest]) (*connect.Response[v1.RemoveDependencyResponse], error)
	// ListDependencies returns all edges where the given state is the consumer (incoming deps).
	ListDependencies(context.Context, *connect.Request[v1.ListDependenciesRequest]) (*connect.Response[v1.ListDependenciesResponse], error)
	// ListDependents returns all edges where the given state is the producer (outgoing deps).
	ListDependents(context.Context, *connect.Request[v1.ListDependentsRequest]) (*connect.Response[v1.ListDependentsResponse], error)
	// SearchByOutput finds all edges that reference a specific output key (by name).
	SearchByOutput(context.Context, *connect.Request[v1.SearchByOutputRequest]) (*connect.Response[v1.SearchByOutputResponse], error)
	// GetTopologicalOrder computes layered ordering of states rooted at given state.
	GetTopologicalOrder(context.Context, *connect.Request[v1.GetTopologicalOrderRequest]) (*connect.Response[v1.GetTopologicalOrderResponse], error)
	// GetStateStatus computes on-demand status for a state based on its incoming edges.
	GetStateStatus(context.Context, *connect.Request[v1.GetStateStatusRequest]) (*connect.Response[v1.GetStateStatusResponse], error)
	// GetDependencyGraph returns full dependency graph data for client-side HCL generation.
	GetDependencyGraph(context.Context, *connect.Request[v1.GetDependencyGraphRequest]) (*connect.Response[v1.GetDependencyGraphResponse], error)
	// ListStateOutputs returns available output keys from a state's Terraform/OpenTofu JSON.
	// Output values are NOT returned (security/size concerns); only keys and sensitive flags.
	// Used by CLI for interactive output selection when creating dependencies.
	ListStateOutputs(context.Context, *connect.Request[v1.ListStateOutputsRequest]) (*connect.Response[v1.ListStateOutputsResponse], error)
	// GetStateInfo retrieves comprehensive state information including:
	// - Basic metadata (GUID, logic-id, timestamps)
	// - Backend configuration (Terraform HTTP backend URLs)
	// - Dependencies (incoming edges: states this state depends on)
	// - Dependents (outgoing edges: states that depend on this state)
	// - Outputs (available Terraform output keys from state JSON)
	//
	// This consolidates information previously requiring multiple RPC calls.
	GetStateInfo(context.Context, *connect.Request[v1.GetStateInfoRequest]) (*connect.Response[v1.GetStateInfoResponse], error)
	// ListAllEdges returns all dependency edges in the system.
	// Used by dashboards and monitoring tools to visualize complete topology.
	// Returns edges in ascending order by ID (database insertion order).
	ListAllEdges(context.Context, *connect.Request[v1.ListAllEdgesRequest]) (*connect.Response[v1.ListAllEdgesResponse], error)
	// UpdateStateLabels mutates labels for an existing state (add/replace/remove).
	UpdateStateLabels(context.Context, *connect.Request[v1.UpdateStateLabelsRequest]) (*connect.Response[v1.UpdateStateLabelsResponse], error)
	// GetLabelPolicy retrieves the current label validation policy.
	GetLabelPolicy(context.Context, *connect.Request[v1.GetLabelPolicyRequest]) (*connect.Response[v1.GetLabelPolicyResponse], error)
	// SetLabelPolicy updates the label validation policy with version increment.
	SetLabelPolicy(context.Context, *connect.Request[v1.SetLabelPolicyRequest]) (*connect.Response[v1.SetLabelPolicyResponse], error)
	// Service Account Management
	CreateServiceAccount(context.Context, *connect.Request[v1.CreateServiceAccountRequest]) (*connect.Response[v1.CreateServiceAccountResponse], error)
	ListServiceAccounts(context.Context, *connect.Request[v1.ListServiceAccountsRequest]) (*connect.Response[v1.ListServiceAccountsResponse], error)
	RevokeServiceAccount(context.Context, *connect.Request[v1.RevokeServiceAccountRequest]) (*connect.Response[v1.RevokeServiceAccountResponse], error)
	RotateServiceAccount(context.Context, *connect.Request[v1.RotateServiceAccountRequest]) (*connect.Response[v1.RotateServiceAccountResponse], error)
	// Role Management
	CreateRole(context.Context, *connect.Request[v1.CreateRoleRequest]) (*connect.Response[v1.CreateRoleResponse], error)
	ListRoles(context.Context, *connect.Request[v1.ListRolesRequest]) (*connect.Response[v1.ListRolesResponse], error)
	UpdateRole(context.Context, *connect.Request[v1.UpdateRoleRequest]) (*connect.Response[v1.UpdateRoleResponse], error)
	DeleteRole(context.Context, *connect.Request[v1.DeleteRoleRequest]) (*connect.Response[v1.DeleteRoleResponse], error)
	// Role Assignment (User/Service Account)
	AssignRole(context.Context, *connect.Request[v1.AssignRoleRequest]) (*connect.Response[v1.AssignRoleResponse], error)
	RemoveRole(context.Context, *connect.Request[v1.RemoveRoleRequest]) (*connect.Response[v1.RemoveRoleResponse], error)
	ListUserRoles(context.Context, *connect.Request[v1.ListUserRolesRequest]) (*connect.Response[v1.ListUserRolesResponse], error)
	// Group-to-Role Management
	AssignGroupRole(context.Context, *connect.Request[v1.AssignGroupRoleRequest]) (*connect.Response[v1.AssignGroupRoleResponse], error)
	RemoveGroupRole(context.Context, *connect.Request[v1.RemoveGroupRoleRequest]) (*connect.Response[v1.RemoveGroupRoleResponse], error)
	ListGroupRoles(context.Context, *connect.Request[v1.ListGroupRolesRequest]) (*connect.Response[v1.ListGroupRolesResponse], error)
	// Permission Introspection
	GetEffectivePermissions(context.Context, *connect.Request[v1.GetEffectivePermissionsRequest]) (*connect.Response[v1.GetEffectivePermissionsResponse], error)
	// Session Management
	ListSessions(context.Context, *connect.Request[v1.ListSessionsRequest]) (*connect.Response[v1.ListSessionsResponse], error)
	RevokeSession(context.Context, *connect.Request[v1.RevokeSessionRequest]) (*connect.Response[v1.RevokeSessionResponse], error)
	// SetOutputSchema publishes or updates a JSON Schema for a specific state output.
	// This allows clients to declare expected output types before the output exists.
	SetOutputSchema(context.Context, *connect.Request[v1.SetOutputSchemaRequest]) (*connect.Response[v1.SetOutputSchemaResponse], error)
	// GetOutputSchema retrieves the JSON Schema for a specific state output.
	GetOutputSchema(context.Context, *connect.Request[v1.GetOutputSchemaRequest]) (*connect.Response[v1.GetOutputSchemaResponse], error)
}

// NewStateServiceClient constructs a client for the state.v1.StateService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewStateServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) StateServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	stateServiceMethods := v1.File_state_v1_state_proto.Services().ByName("StateService").Methods()
	return &stateServiceClient{
		createState: connect.NewClient[v1.CreateStateRequest, v1.CreateStateResponse](
			httpClient,
			baseURL+StateServiceCreateStateProcedure,
			connect.WithSchema(stateServiceMethods.ByName("CreateState")),
			connect.WithClientOptions(opts...),
		),
		listStates: connect.NewClient[v1.ListStatesRequest, v1.ListStatesResponse](
			httpClient,
			baseURL+StateServiceListStatesProcedure,
			connect.WithSchema(stateServiceMethods.ByName("ListStates")),
			connect.WithClientOptions(opts...),
		),
		getStateConfig: connect.NewClient[v1.GetStateConfigRequest, v1.GetStateConfigResponse](
			httpClient,
			baseURL+StateServiceGetStateConfigProcedure,
			connect.WithSchema(stateServiceMethods.ByName("GetStateConfig")),
			connect.WithClientOptions(opts...),
		),
		getStateLock: connect.NewClient[v1.GetStateLockRequest, v1.GetStateLockResponse](
			httpClient,
			baseURL+StateServiceGetStateLockProcedure,
			connect.WithSchema(stateServiceMethods.ByName("GetStateLock")),
			connect.WithClientOptions(opts...),
		),
		unlockState: connect.NewClient[v1.UnlockStateRequest, v1.UnlockStateResponse](
			httpClient,
			baseURL+StateServiceUnlockStateProcedure,
			connect.WithSchema(stateServiceMethods.ByName("UnlockState")),
			connect.WithClientOptions(opts...),
		),
		addDependency: connect.NewClient[v1.AddDependencyRequest, v1.AddDependencyResponse](
			httpClient,
			baseURL+StateServiceAddDependencyProcedure,
			connect.WithSchema(stateServiceMethods.ByName("AddDependency")),
			connect.WithClientOptions(opts...),
		),
		removeDependency: connect.NewClient[v1.RemoveDependencyRequest, v1.RemoveDependencyResponse](
			httpClient,
			baseURL+StateServiceRemoveDependencyProcedure,
			connect.WithSchema(stateServiceMethods.ByName("RemoveDependency")),
			connect.WithClientOptions(opts...),
		),
		listDependencies: connect.NewClient[v1.ListDependenciesRequest, v1.ListDependenciesResponse](
			httpClient,
			baseURL+StateServiceListDependenciesProcedure,
			connect.WithSchema(stateServiceMethods.ByName("ListDependencies")),
			connect.WithClientOptions(opts...),
		),
		listDependents: connect.NewClient[v1.ListDependentsRequest, v1.ListDependentsResponse](
			httpClient,
			baseURL+StateServiceListDependentsProcedure,
			connect.WithSchema(stateServiceMethods.ByName("ListDependents")),
			connect.WithClientOptions(opts...),
		),
		searchByOutput: connect.NewClient[v1.SearchByOutputRequest, v1.SearchByOutputResponse](
			httpClient,
			baseURL+StateServiceSearchByOutputProcedure,
			connect.WithSchema(stateServiceMethods.ByName("SearchByOutput")),
			connect.WithClientOptions(opts...),
		),
		getTopologicalOrder: connect.NewClient[v1.GetTopologicalOrderRequest, v1.GetTopologicalOrderResponse](
			httpClient,
			baseURL+StateServiceGetTopologicalOrderProcedure,
			connect.WithSchema(stateServiceMethods.ByName("GetTopologicalOrder")),
			connect.WithClientOptions(opts...),
		),
		getStateStatus: connect.NewClient[v1.GetStateStatusRequest, v1.GetStateStatusResponse](
			httpClient,
			baseURL+StateServiceGetStateStatusProcedure,
			connect.WithSchema(stateServiceMethods.ByName("GetStateStatus")),
			connect.WithClientOptions(opts...),
		),
		getDependencyGraph: connect.NewClient[v1.GetDependencyGraphRequest, v1.GetDependencyGraphResponse](
			httpClient,
			baseURL+StateServiceGetDependencyGraphProcedure,
			connect.WithSchema(stateServiceMethods.ByName("GetDependencyGraph")),
			connect.WithClientOptions(opts...),
		),
		listStateOutputs: connect.NewClient[v1.ListStateOutputsRequest, v1.ListStateOutputsResponse](
			httpClient,
			baseURL+StateServiceListStateOutputsProcedure,
			connect.WithSchema(stateServiceMethods.ByName("ListStateOutputs")),
			connect.WithClientOptions(opts...),
		),
		getStateInfo: connect.NewClient[v1.GetStateInfoRequest, v1.GetStateInfoResponse](
			httpClient,
			baseURL+StateServiceGetStateInfoProcedure,
			connect.WithSchema(stateServiceMethods.ByName("GetStateInfo")),
			connect.WithClientOptions(opts...),
		),
		listAllEdges: connect.NewClient[v1.ListAllEdgesRequest, v1.ListAllEdgesResponse](
			httpClient,
			baseURL+StateServiceListAllEdgesProcedure,
			connect.WithSchema(stateServiceMethods.ByName("ListAllEdges")),
			connect.WithClientOptions(opts...),
		),
		updateStateLabels: connect.NewClient[v1.UpdateStateLabelsRequest, v1.UpdateStateLabelsResponse](
			httpClient,
			baseURL+StateServiceUpdateStateLabelsProcedure,
			connect.WithSchema(stateServiceMethods.ByName("UpdateStateLabels")),
			connect.WithClientOptions(opts...),
		),
		getLabelPolicy: connect.NewClient[v1.GetLabelPolicyRequest, v1.GetLabelPolicyResponse](
			httpClient,
			baseURL+StateServiceGetLabelPolicyProcedure,
			connect.WithSchema(stateServiceMethods.ByName("GetLabelPolicy")),
			connect.WithClientOptions(opts...),
		),
		setLabelPolicy: connect.NewClient[v1.SetLabelPolicyRequest, v1.SetLabelPolicyResponse](
			httpClient,
			baseURL+StateServiceSetLabelPolicyProcedure,
			connect.WithSchema(stateServiceMethods.ByName("SetLabelPolicy")),
			connect.WithClientOptions(opts...),
		),
		createServiceAccount: connect.NewClient[v1.CreateServiceAccountRequest, v1.CreateServiceAccountResponse](
			httpClient,
			baseURL+StateServiceCreateServiceAccountProcedure,
			connect.WithSchema(stateServiceMethods.ByName("CreateServiceAccount")),
			connect.WithClientOptions(opts...),
		),
		listServiceAccounts: connect.NewClient[v1.ListServiceAccountsRequest, v1.ListServiceAccountsResponse](
			httpClient,
			baseURL+StateServiceListServiceAccountsProcedure,
			connect.WithSchema(stateServiceMethods.ByName("ListServiceAccounts")),
			connect.WithClientOptions(opts...),
		),
		revokeServiceAccount: connect.NewClient[v1.RevokeServiceAccountRequest, v1.RevokeServiceAccountResponse](
			httpClient,
			baseURL+StateServiceRevokeServiceAccountProcedure,
			connect.WithSchema(stateServiceMethods.ByName("RevokeServiceAccount")),
			connect.WithClientOptions(opts...),
		),
		rotateServiceAccount: connect.NewClient[v1.RotateServiceAccountRequest, v1.RotateServiceAccountResponse](
			httpClient,
			baseURL+StateServiceRotateServiceAccountProcedure,
			connect.WithSchema(stateServiceMethods.ByName("RotateServiceAccount")),
			connect.WithClientOptions(opts...),
		),
		createRole: connect.NewClient[v1.CreateRoleRequest, v1.CreateRoleResponse](
			httpClient,
			baseURL+StateServiceCreateRoleProcedure,
			connect.WithSchema(stateServiceMethods.ByName("CreateRole")),
			connect.WithClientOptions(opts...),
		),
		listRoles: connect.NewClient[v1.ListRolesRequest, v1.ListRolesResponse](
			httpClient,
			baseURL+StateServiceListRolesProcedure,
			connect.WithSchema(stateServiceMethods.ByName("ListRoles")),
			connect.WithClientOptions(opts...),
		),
		updateRole: connect.NewClient[v1.UpdateRoleRequest, v1.UpdateRoleResponse](
			httpClient,
			baseURL+StateServiceUpdateRoleProcedure,
			connect.WithSchema(stateServiceMethods.ByName("UpdateRole")),
			connect.WithClientOptions(opts...),
		),
		deleteRole: connect.NewClient[v1.DeleteRoleRequest, v1.DeleteRoleResponse](
			httpClient,
			baseURL+StateServiceDeleteRoleProcedure,
			connect.WithSchema(stateServiceMethods.ByName("DeleteRole")),
			connect.WithClientOptions(opts...),
		),
		assignRole: connect.NewClient[v1.AssignRoleRequest, v1.AssignRoleResponse](
			httpClient,
			baseURL+StateServiceAssignRoleProcedure,
			connect.WithSchema(stateServiceMethods.ByName("AssignRole")),
			connect.WithClientOptions(opts...),
		),
		removeRole: connect.NewClient[v1.RemoveRoleRequest, v1.RemoveRoleResponse](
			httpClient,
			baseURL+StateServiceRemoveRoleProcedure,
			connect.WithSchema(stateServiceMethods.ByName("RemoveRole")),
			connect.WithClientOptions(opts...),
		),
		listUserRoles: connect.NewClient[v1.ListUserRolesRequest, v1.ListUserRolesResponse](
			httpClient,
			baseURL+StateServiceListUserRolesProcedure,
			connect.WithSchema(stateServiceMethods.ByName("ListUserRoles")),
			connect.WithClientOptions(opts...),
		),
		assignGroupRole: connect.NewClient[v1.AssignGroupRoleRequest, v1.AssignGroupRoleResponse](
			httpClient,
			baseURL+StateServiceAssignGroupRoleProcedure,
			connect.WithSchema(stateServiceMethods.ByName("AssignGroupRole")),
			connect.WithClientOptions(opts...),
		),
		removeGroupRole: connect.NewClient[v1.RemoveGroupRoleRequest, v1.RemoveGroupRoleResponse](
			httpClient,
			baseURL+StateServiceRemoveGroupRoleProcedure,
			connect.WithSchema(stateServiceMethods.ByName("RemoveGroupRole")),
			connect.WithClientOptions(opts...),
		),
		listGroupRoles: connect.NewClient[v1.ListGroupRolesRequest, v1.ListGroupRolesResponse](
			httpClient,
			baseURL+StateServiceListGroupRolesProcedure,
			connect.WithSchema(stateServiceMethods.ByName("ListGroupRoles")),
			connect.WithClientOptions(opts...),
		),
		getEffectivePermissions: connect.NewClient[v1.GetEffectivePermissionsRequest, v1.GetEffectivePermissionsResponse](
			httpClient,
			baseURL+StateServiceGetEffectivePermissionsProcedure,
			connect.WithSchema(stateServiceMethods.ByName("GetEffectivePermissions")),
			connect.WithClientOptions(opts...),
		),
		listSessions: connect.NewClient[v1.ListSessionsRequest, v1.ListSessionsResponse](
			httpClient,
			baseURL+StateServiceListSessionsProcedure,
			connect.WithSchema(stateServiceMethods.ByName("ListSessions")),
			connect.WithClientOptions(opts...),
		),
		revokeSession: connect.NewClient[v1.RevokeSessionRequest, v1.RevokeSessionResponse](
			httpClient,
			baseURL+StateServiceRevokeSessionProcedure,
			connect.WithSchema(stateServiceMethods.ByName("RevokeSession")),
			connect.WithClientOptions(opts...),
		),
		setOutputSchema: connect.NewClient[v1.SetOutputSchemaRequest, v1.SetOutputSchemaResponse](
			httpClient,
			baseURL+StateServiceSetOutputSchemaProcedure,
			connect.WithSchema(stateServiceMethods.ByName("SetOutputSchema")),
			connect.WithClientOptions(opts...),
		),
		getOutputSchema: connect.NewClient[v1.GetOutputSchemaRequest, v1.GetOutputSchemaResponse](
			httpClient,
			baseURL+StateServiceGetOutputSchemaProcedure,
			connect.WithSchema(stateServiceMethods.ByName("GetOutputSchema")),
			connect.WithClientOptions(opts...),
		),
	}
}

// stateServiceClient implements StateServiceClient.
type stateServiceClient struct {
	createState             *connect.Client[v1.CreateStateRequest, v1.CreateStateResponse]
	listStates              *connect.Client[v1.ListStatesRequest, v1.ListStatesResponse]
	getStateConfig          *connect.Client[v1.GetStateConfigRequest, v1.GetStateConfigResponse]
	getStateLock            *connect.Client[v1.GetStateLockRequest, v1.GetStateLockResponse]
	unlockState             *connect.Client[v1.UnlockStateRequest, v1.UnlockStateResponse]
	addDependency           *connect.Client[v1.AddDependencyRequest, v1.AddDependencyResponse]
	removeDependency        *connect.Client[v1.RemoveDependencyRequest, v1.RemoveDependencyResponse]
	listDependencies        *connect.Client[v1.ListDependenciesRequest, v1.ListDependenciesResponse]
	listDependents          *connect.Client[v1.ListDependentsRequest, v1.ListDependentsResponse]
	searchByOutput          *connect.Client[v1.SearchByOutputRequest, v1.SearchByOutputResponse]
	getTopologicalOrder     *connect.Client[v1.GetTopologicalOrderRequest, v1.GetTopologicalOrderResponse]
	getStateStatus          *connect.Client[v1.GetStateStatusRequest, v1.GetStateStatusResponse]
	getDependencyGraph      *connect.Client[v1.GetDependencyGraphRequest, v1.GetDependencyGraphResponse]
	listStateOutputs        *connect.Client[v1.ListStateOutputsRequest, v1.ListStateOutputsResponse]
	getStateInfo            *connect.Client[v1.GetStateInfoRequest, v1.GetStateInfoResponse]
	listAllEdges            *connect.Client[v1.ListAllEdgesRequest, v1.ListAllEdgesResponse]
	updateStateLabels       *connect.Client[v1.UpdateStateLabelsRequest, v1.UpdateStateLabelsResponse]
	getLabelPolicy          *connect.Client[v1.GetLabelPolicyRequest, v1.GetLabelPolicyResponse]
	setLabelPolicy          *connect.Client[v1.SetLabelPolicyRequest, v1.SetLabelPolicyResponse]
	createServiceAccount    *connect.Client[v1.CreateServiceAccountRequest, v1.CreateServiceAccountResponse]
	listServiceAccounts     *connect.Client[v1.ListServiceAccountsRequest, v1.ListServiceAccountsResponse]
	revokeServiceAccount    *connect.Client[v1.RevokeServiceAccountRequest, v1.RevokeServiceAccountResponse]
	rotateServiceAccount    *connect.Client[v1.RotateServiceAccountRequest, v1.RotateServiceAccountResponse]
	createRole              *connect.Client[v1.CreateRoleRequest, v1.CreateRoleResponse]
	listRoles               *connect.Client[v1.ListRolesRequest, v1.ListRolesResponse]
	updateRole              *connect.Client[v1.UpdateRoleRequest, v1.UpdateRoleResponse]
	deleteRole              *connect.Client[v1.DeleteRoleRequest, v1.DeleteRoleResponse]
	assignRole              *connect.Client[v1.AssignRoleRequest, v1.AssignRoleResponse]
	removeRole              *connect.Client[v1.RemoveRoleRequest, v1.RemoveRoleResponse]
	listUserRoles           *connect.Client[v1.ListUserRolesRequest, v1.ListUserRolesResponse]
	assignGroupRole         *connect.Client[v1.AssignGroupRoleRequest, v1.AssignGroupRoleResponse]
	removeGroupRole         *connect.Client[v1.RemoveGroupRoleRequest, v1.RemoveGroupRoleResponse]
	listGroupRoles          *connect.Client[v1.ListGroupRolesRequest, v1.ListGroupRolesResponse]
	getEffectivePermissions *connect.Client[v1.GetEffectivePermissionsRequest, v1.GetEffectivePermissionsResponse]
	listSessions            *connect.Client[v1.ListSessionsRequest, v1.ListSessionsResponse]
	revokeSession           *connect.Client[v1.RevokeSessionRequest, v1.RevokeSessionResponse]
	setOutputSchema         *connect.Client[v1.SetOutputSchemaRequest, v1.SetOutputSchemaResponse]
	getOutputSchema         *connect.Client[v1.GetOutputSchemaRequest, v1.GetOutputSchemaResponse]
}

// CreateState calls state.v1.StateService.CreateState.
func (c *stateServiceClient) CreateState(ctx context.Context, req *connect.Request[v1.CreateStateRequest]) (*connect.Response[v1.CreateStateResponse], error) {
	return c.createState.CallUnary(ctx, req)
}

// ListStates calls state.v1.StateService.ListStates.
func (c *stateServiceClient) ListStates(ctx context.Context, req *connect.Request[v1.ListStatesRequest]) (*connect.Response[v1.ListStatesResponse], error) {
	return c.listStates.CallUnary(ctx, req)
}

// GetStateConfig calls state.v1.StateService.GetStateConfig.
func (c *stateServiceClient) GetStateConfig(ctx context.Context, req *connect.Request[v1.GetStateConfigRequest]) (*connect.Response[v1.GetStateConfigResponse], error) {
	return c.getStateConfig.CallUnary(ctx, req)
}

// GetStateLock calls state.v1.StateService.GetStateLock.
func (c *stateServiceClient) GetStateLock(ctx context.Context, req *connect.Request[v1.GetStateLockRequest]) (*connect.Response[v1.GetStateLockResponse], error) {
	return c.getStateLock.CallUnary(ctx, req)
}

// UnlockState calls state.v1.StateService.UnlockState.
func (c *stateServiceClient) UnlockState(ctx context.Context, req *connect.Request[v1.UnlockStateRequest]) (*connect.Response[v1.UnlockStateResponse], error) {
	return c.unlockState.CallUnary(ctx, req)
}

// AddDependency calls state.v1.StateService.AddDependency.
func (c *stateServiceClient) AddDependency(ctx context.Context, req *connect.Request[v1.AddDependencyRequest]) (*connect.Response[v1.AddDependencyResponse], error) {
	return c.addDependency.CallUnary(ctx, req)
}

// RemoveDependency calls state.v1.StateService.RemoveDependency.
func (c *stateServiceClient) RemoveDependency(ctx context.Context, req *connect.Request[v1.RemoveDependencyRequest]) (*connect.Response[v1.RemoveDependencyResponse], error) {
	return c.removeDependency.CallUnary(ctx, req)
}

// ListDependencies calls state.v1.StateService.ListDependencies.
func (c *stateServiceClient) ListDependencies(ctx context.Context, req *connect.Request[v1.ListDependenciesRequest]) (*connect.Response[v1.ListDependenciesResponse], error) {
	return c.listDependencies.CallUnary(ctx, req)
}

// ListDependents calls state.v1.StateService.ListDependents.
func (c *stateServiceClient) ListDependents(ctx context.Context, req *connect.Request[v1.ListDependentsRequest]) (*connect.Response[v1.ListDependentsResponse], error) {
	return c.listDependents.CallUnary(ctx, req)
}

// SearchByOutput calls state.v1.StateService.SearchByOutput.
func (c *stateServiceClient) SearchByOutput(ctx context.Context, req *connect.Request[v1.SearchByOutputRequest]) (*connect.Response[v1.SearchByOutputResponse], error) {
	return c.searchByOutput.CallUnary(ctx, req)
}

// GetTopologicalOrder calls state.v1.StateService.GetTopologicalOrder.
func (c *stateServiceClient) GetTopologicalOrder(ctx context.Context, req *connect.Request[v1.GetTopologicalOrderRequest]) (*connect.Response[v1.GetTopologicalOrderResponse], error) {
	return c.getTopologicalOrder.CallUnary(ctx, req)
}

// GetStateStatus calls state.v1.StateService.GetStateStatus.
func (c *stateServiceClient) GetStateStatus(ctx context.Context, req *connect.Request[v1.GetStateStatusRequest]) (*connect.Response[v1.GetStateStatusResponse], error) {
	return c.getStateStatus.CallUnary(ctx, req)
}

// GetDependencyGraph calls state.v1.StateService.GetDependencyGraph.
func (c *stateServiceClient) GetDependencyGraph(ctx context.Context, req *connect.Request[v1.GetDependencyGraphRequest]) (*connect.Response[v1.GetDependencyGraphResponse], error) {
	return c.getDependencyGraph.CallUnary(ctx, req)
}

// ListStateOutputs calls state.v1.StateService.ListStateOutputs.
func (c *stateServiceClient) ListStateOutputs(ctx context.Context, req *connect.Request[v1.ListStateOutputsRequest]) (*connect.Response[v1.ListStateOutputsResponse], error) {
	return c.listStateOutputs.CallUnary(ctx, req)
}

// GetStateInfo calls state.v1.StateService.GetStateInfo.
func (c *stateServiceClient) GetStateInfo(ctx context.Context, req *connect.Request[v1.GetStateInfoRequest]) (*connect.Response[v1.GetStateInfoResponse], error) {
	return c.getStateInfo.CallUnary(ctx, req)
}

// ListAllEdges calls state.v1.StateService.ListAllEdges.
func (c *stateServiceClient) ListAllEdges(ctx context.Context, req *connect.Request[v1.ListAllEdgesRequest]) (*connect.Response[v1.ListAllEdgesResponse], error) {
	return c.listAllEdges.CallUnary(ctx, req)
}

// UpdateStateLabels calls state.v1.StateService.UpdateStateLabels.
func (c *stateServiceClient) UpdateStateLabels(ctx context.Context, req *connect.Request[v1.UpdateStateLabelsRequest]) (*connect.Response[v1.UpdateStateLabelsResponse], error) {
	return c.updateStateLabels.CallUnary(ctx, req)
}

// GetLabelPolicy calls state.v1.StateService.GetLabelPolicy.
func (c *stateServiceClient) GetLabelPolicy(ctx context.Context, req *connect.Request[v1.GetLabelPolicyRequest]) (*connect.Response[v1.GetLabelPolicyResponse], error) {
	return c.getLabelPolicy.CallUnary(ctx, req)
}

// SetLabelPolicy calls state.v1.StateService.SetLabelPolicy.
func (c *stateServiceClient) SetLabelPolicy(ctx context.Context, req *connect.Request[v1.SetLabelPolicyRequest]) (*connect.Response[v1.SetLabelPolicyResponse], error) {
	return c.setLabelPolicy.CallUnary(ctx, req)
}

// CreateServiceAccount calls state.v1.StateService.CreateServiceAccount.
func (c *stateServiceClient) CreateServiceAccount(ctx context.Context, req *connect.Request[v1.CreateServiceAccountRequest]) (*connect.Response[v1.CreateServiceAccountResponse], error) {
	return c.createServiceAccount.CallUnary(ctx, req)
}

// ListServiceAccounts calls state.v1.StateService.ListServiceAccounts.
func (c *stateServiceClient) ListServiceAccounts(ctx context.Context, req *connect.Request[v1.ListServiceAccountsRequest]) (*connect.Response[v1.ListServiceAccountsResponse], error) {
	return c.listServiceAccounts.CallUnary(ctx, req)
}

// RevokeServiceAccount calls state.v1.StateService.RevokeServiceAccount.
func (c *stateServiceClient) RevokeServiceAccount(ctx context.Context, req *connect.Request[v1.RevokeServiceAccountRequest]) (*connect.Response[v1.RevokeServiceAccountResponse], error) {
	return c.revokeServiceAccount.CallUnary(ctx, req)
}

// RotateServiceAccount calls state.v1.StateService.RotateServiceAccount.
func (c *stateServiceClient) RotateServiceAccount(ctx context.Context, req *connect.Request[v1.RotateServiceAccountRequest]) (*connect.Response[v1.RotateServiceAccountResponse], error) {
	return c.rotateServiceAccount.CallUnary(ctx, req)
}

// CreateRole calls state.v1.StateService.CreateRole.
func (c *stateServiceClient) CreateRole(ctx context.Context, req *connect.Request[v1.CreateRoleRequest]) (*connect.Response[v1.CreateRoleResponse], error) {
	return c.createRole.CallUnary(ctx, req)
}

// ListRoles calls state.v1.StateService.ListRoles.
func (c *stateServiceClient) ListRoles(ctx context.Context, req *connect.Request[v1.ListRolesRequest]) (*connect.Response[v1.ListRolesResponse], error) {
	return c.listRoles.CallUnary(ctx, req)
}

// UpdateRole calls state.v1.StateService.UpdateRole.
func (c *stateServiceClient) UpdateRole(ctx context.Context, req *connect.Request[v1.UpdateRoleRequest]) (*connect.Response[v1.UpdateRoleResponse], error) {
	return c.updateRole.CallUnary(ctx, req)
}

// DeleteRole calls state.v1.StateService.DeleteRole.
func (c *stateServiceClient) DeleteRole(ctx context.Context, req *connect.Request[v1.DeleteRoleRequest]) (*connect.Response[v1.DeleteRoleResponse], error) {
	return c.deleteRole.CallUnary(ctx, req)
}

// AssignRole calls state.v1.StateService.AssignRole.
func (c *stateServiceClient) AssignRole(ctx context.Context, req *connect.Request[v1.AssignRoleRequest]) (*connect.Response[v1.AssignRoleResponse], error) {
	return c.assignRole.CallUnary(ctx, req)
}

// RemoveRole calls state.v1.StateService.RemoveRole.
func (c *stateServiceClient) RemoveRole(ctx context.Context, req *connect.Request[v1.RemoveRoleRequest]) (*connect.Response[v1.RemoveRoleResponse], error) {
	return c.removeRole.CallUnary(ctx, req)
}

// ListUserRoles calls state.v1.StateService.ListUserRoles.
func (c *stateServiceClient) ListUserRoles(ctx context.Context, req *connect.Request[v1.ListUserRolesRequest]) (*connect.Response[v1.ListUserRolesResponse], error) {
	return c.listUserRoles.CallUnary(ctx, req)
}

// AssignGroupRole calls state.v1.StateService.AssignGroupRole.
func (c *stateServiceClient) AssignGroupRole(ctx context.Context, req *connect.Request[v1.AssignGroupRoleRequest]) (*connect.Response[v1.AssignGroupRoleResponse], error) {
	return c.assignGroupRole.CallUnary(ctx, req)
}

// RemoveGroupRole calls state.v1.StateService.RemoveGroupRole.
func (c *stateServiceClient) RemoveGroupRole(ctx context.Context, req *connect.Request[v1.RemoveGroupRoleRequest]) (*connect.Response[v1.RemoveGroupRoleResponse], error) {
	return c.removeGroupRole.CallUnary(ctx, req)
}

// ListGroupRoles calls state.v1.StateService.ListGroupRoles.
func (c *stateServiceClient) ListGroupRoles(ctx context.Context, req *connect.Request[v1.ListGroupRolesRequest]) (*connect.Response[v1.ListGroupRolesResponse], error) {
	return c.listGroupRoles.CallUnary(ctx, req)
}

// GetEffectivePermissions calls state.v1.StateService.GetEffectivePermissions.
func (c *stateServiceClient) GetEffectivePermissions(ctx context.Context, req *connect.Request[v1.GetEffectivePermissionsRequest]) (*connect.Response[v1.GetEffectivePermissionsResponse], error) {
	return c.getEffectivePermissions.CallUnary(ctx, req)
}

// ListSessions calls state.v1.StateService.ListSessions.
func (c *stateServiceClient) ListSessions(ctx context.Context, req *connect.Request[v1.ListSessionsRequest]) (*connect.Response[v1.ListSessionsResponse], error) {
	return c.listSessions.CallUnary(ctx, req)
}

// RevokeSession calls state.v1.StateService.RevokeSession.
func (c *stateServiceClient) RevokeSession(ctx context.Context, req *connect.Request[v1.RevokeSessionRequest]) (*connect.Response[v1.RevokeSessionResponse], error) {
	return c.revokeSession.CallUnary(ctx, req)
}

// SetOutputSchema calls state.v1.StateService.SetOutputSchema.
func (c *stateServiceClient) SetOutputSchema(ctx context.Context, req *connect.Request[v1.SetOutputSchemaRequest]) (*connect.Response[v1.SetOutputSchemaResponse], error) {
	return c.setOutputSchema.CallUnary(ctx, req)
}

// GetOutputSchema calls state.v1.StateService.GetOutputSchema.
func (c *stateServiceClient) GetOutputSchema(ctx context.Context, req *connect.Request[v1.GetOutputSchemaRequest]) (*connect.Response[v1.GetOutputSchemaResponse], error) {
	return c.getOutputSchema.CallUnary(ctx, req)
}

// StateServiceHandler is an implementation of the state.v1.StateService service.
type StateServiceHandler interface {
	// CreateState creates a new state with client-generated GUID and logic ID.
	CreateState(context.Context, *connect.Request[v1.CreateStateRequest]) (*connect.Response[v1.CreateStateResponse], error)
	// ListStates returns all states with summary information.
	ListStates(context.Context, *connect.Request[v1.ListStatesRequest]) (*connect.Response[v1.ListStatesResponse], error)
	// GetStateConfig retrieves backend configuration for an existing state by logic ID.
	GetStateConfig(context.Context, *connect.Request[v1.GetStateConfigRequest]) (*connect.Response[v1.GetStateConfigResponse], error)
	// GetStateLock inspects the current lock metadata for a state by GUID.
	GetStateLock(context.Context, *connect.Request[v1.GetStateLockRequest]) (*connect.Response[v1.GetStateLockResponse], error)
	// UnlockState releases a lock using the lock ID provided by Terraform/OpenTofu.
	UnlockState(context.Context, *connect.Request[v1.UnlockStateRequest]) (*connect.Response[v1.UnlockStateResponse], error)
	// AddDependency declares a dependency edge from producer output to consumer state.
	// Returns existing edge if duplicate (idempotent). Rejects if would create cycle.
	AddDependency(context.Context, *connect.Request[v1.AddDependencyRequest]) (*connect.Response[v1.AddDependencyResponse], error)
	// RemoveDependency deletes a dependency edge by ID.
	RemoveDependency(context.Context, *connect.Request[v1.RemoveDependencyRequest]) (*connect.Response[v1.RemoveDependencyResponse], error)
	// ListDependencies returns all edges where the given state is the consumer (incoming deps).
	ListDependencies(context.Context, *connect.Request[v1.ListDependenciesRequest]) (*connect.Response[v1.ListDependenciesResponse], error)
	// ListDependents returns all edges where the given state is the producer (outgoing deps).
	ListDependents(context.Context, *connect.Request[v1.ListDependentsRequest]) (*connect.Response[v1.ListDependentsResponse], error)
	// SearchByOutput finds all edges that reference a specific output key (by name).
	SearchByOutput(context.Context, *connect.Request[v1.SearchByOutputRequest]) (*connect.Response[v1.SearchByOutputResponse], error)
	// GetTopologicalOrder computes layered ordering of states rooted at given state.
	GetTopologicalOrder(context.Context, *connect.Request[v1.GetTopologicalOrderRequest]) (*connect.Response[v1.GetTopologicalOrderResponse], error)
	// GetStateStatus computes on-demand status for a state based on its incoming edges.
	GetStateStatus(context.Context, *connect.Request[v1.GetStateStatusRequest]) (*connect.Response[v1.GetStateStatusResponse], error)
	// GetDependencyGraph returns full dependency graph data for client-side HCL generation.
	GetDependencyGraph(context.Context, *connect.Request[v1.GetDependencyGraphRequest]) (*connect.Response[v1.GetDependencyGraphResponse], error)
	// ListStateOutputs returns available output keys from a state's Terraform/OpenTofu JSON.
	// Output values are NOT returned (security/size concerns); only keys and sensitive flags.
	// Used by CLI for interactive output selection when creating dependencies.
	ListStateOutputs(context.Context, *connect.Request[v1.ListStateOutputsRequest]) (*connect.Response[v1.ListStateOutputsResponse], error)
	// GetStateInfo retrieves comprehensive state information including:
	// - Basic metadata (GUID, logic-id, timestamps)
	// - Backend configuration (Terraform HTTP backend URLs)
	// - Dependencies (incoming edges: states this state depends on)
	// - Dependents (outgoing edges: states that depend on this state)
	// - Outputs (available Terraform output keys from state JSON)
	//
	// This consolidates information previously requiring multiple RPC calls.
	GetStateInfo(context.Context, *connect.Request[v1.GetStateInfoRequest]) (*connect.Response[v1.GetStateInfoResponse], error)
	// ListAllEdges returns all dependency edges in the system.
	// Used by dashboards and monitoring tools to visualize complete topology.
	// Returns edges in ascending order by ID (database insertion order).
	ListAllEdges(context.Context, *connect.Request[v1.ListAllEdgesRequest]) (*connect.Response[v1.ListAllEdgesResponse], error)
	// UpdateStateLabels mutates labels for an existing state (add/replace/remove).
	UpdateStateLabels(context.Context, *connect.Request[v1.UpdateStateLabelsRequest]) (*connect.Response[v1.UpdateStateLabelsResponse], error)
	// GetLabelPolicy retrieves the current label validation policy.
	GetLabelPolicy(context.Context, *connect.Request[v1.GetLabelPolicyRequest]) (*connect.Response[v1.GetLabelPolicyResponse], error)
	// SetLabelPolicy updates the label validation policy with version increment.
	SetLabelPolicy(context.Context, *connect.Request[v1.SetLabelPolicyRequest]) (*connect.Response[v1.SetLabelPolicyResponse], error)
	// Service Account Management
	CreateServiceAccount(context.Context, *connect.Request[v1.CreateServiceAccountRequest]) (*connect.Response[v1.CreateServiceAccountResponse], error)
	ListServiceAccounts(context.Context, *connect.Request[v1.ListServiceAccountsRequest]) (*connect.Response[v1.ListServiceAccountsResponse], error)
	RevokeServiceAccount(context.Context, *connect.Request[v1.RevokeServiceAccountRequest]) (*connect.Response[v1.RevokeServiceAccountResponse], error)
	RotateServiceAccount(context.Context, *connect.Request[v1.RotateServiceAccountRequest]) (*connect.Response[v1.RotateServiceAccountResponse], error)
	// Role Management
	CreateRole(context.Context, *connect.Request[v1.CreateRoleRequest]) (*connect.Response[v1.CreateRoleResponse], error)
	ListRoles(context.Context, *connect.Request[v1.ListRolesRequest]) (*connect.Response[v1.ListRolesResponse], error)
	UpdateRole(context.Context, *connect.Request[v1.UpdateRoleRequest]) (*connect.Response[v1.UpdateRoleResponse], error)
	DeleteRole(context.Context, *connect.Request[v1.DeleteRoleRequest]) (*connect.Response[v1.DeleteRoleResponse], error)
	// Role Assignment (User/Service Account)
	AssignRole(context.Context, *connect.Request[v1.AssignRoleRequest]) (*connect.Response[v1.AssignRoleResponse], error)
	RemoveRole(context.Context, *connect.Request[v1.RemoveRoleRequest]) (*connect.Response[v1.RemoveRoleResponse], error)
	ListUserRoles(context.Context, *connect.Request[v1.ListUserRolesRequest]) (*connect.Response[v1.ListUserRolesResponse], error)
	// Group-to-Role Management
	AssignGroupRole(context.Context, *connect.Request[v1.AssignGroupRoleRequest]) (*connect.Response[v1.AssignGroupRoleResponse], error)
	RemoveGroupRole(context.Context, *connect.Request[v1.RemoveGroupRoleRequest]) (*connect.Response[v1.RemoveGroupRoleResponse], error)
	ListGroupRoles(context.Context, *connect.Request[v1.ListGroupRolesRequest]) (*connect.Response[v1.ListGroupRolesResponse], error)
	// Permission Introspection
	GetEffectivePermissions(context.Context, *connect.Request[v1.GetEffectivePermissionsRequest]) (*connect.Response[v1.GetEffectivePermissionsResponse], error)
	// Session Management
	ListSessions(context.Context, *connect.Request[v1.ListSessionsRequest]) (*connect.Response[v1.ListSessionsResponse], error)
	RevokeSession(context.Context, *connect.Request[v1.RevokeSessionRequest]) (*connect.Response[v1.RevokeSessionResponse], error)
	// SetOutputSchema publishes or updates a JSON Schema for a specific state output.
	// This allows clients to declare expected output types before the output exists.
	SetOutputSchema(context.Context, *connect.Request[v1.SetOutputSchemaRequest]) (*connect.Response[v1.SetOutputSchemaResponse], error)
	// GetOutputSchema retrieves the JSON Schema for a specific state output.
	GetOutputSchema(context.Context, *connect.Request[v1.GetOutputSchemaRequest]) (*connect.Response[v1.GetOutputSchemaResponse], error)
}

// NewStateServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewStateServiceHandler(svc StateServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	stateServiceMethods := v1.File_state_v1_state_proto.Services().ByName("StateService").Methods()
	stateServiceCreateStateHandler := connect.NewUnaryHandler(
		StateServiceCreateStateProcedure,
		svc.CreateState,
		connect.WithSchema(stateServiceMethods.ByName("CreateState")),
		connect.WithHandlerOptions(opts...),
	)
	stateServiceListStatesHandler := connect.NewUnaryHandler(
		StateServiceListStatesProcedure,
		svc.ListStates,
		connect.WithSchema(stateServiceMethods.ByName("ListStates")),
		connect.WithHandlerOptions(opts...),
	)
	stateServiceGetStateConfigHandler := connect.NewUnaryHandler(
		StateServiceGetStateConfigProcedure,
		svc.GetStateConfig,
		connect.WithSchema(stateServiceMethods.ByName("GetStateConfig")),
		connect.WithHandlerOptions(opts...),
	)
	stateServiceGetStateLockHandler := connect.NewUnaryHandler(
		StateServiceGetStateLockProcedure,
		svc.GetStateLock,
		connect.WithSchema(stateServiceMethods.ByName("GetStateLock")),
		connect.WithHandlerOptions(opts...),
	)
	stateServiceUnlockStateHandler := connect.NewUnaryHandler(
		StateServiceUnlockStateProcedure,
		svc.UnlockState,
		connect.WithSchema(stateServiceMethods.ByName("UnlockState")),
		connect.WithHandlerOptions(opts...),
	)
	stateServiceAddDependencyHandler := connect.NewUnaryHandler(
		StateServiceAddDependencyProcedure,
		svc.AddDependency,
		connect.WithSchema(stateServiceMethods.ByName("AddDependency")),
		connect.WithHandlerOptions(opts...),
	)
	stateServiceRemoveDependencyHandler := connect.NewUnaryHandler(
		StateServiceRemoveDependencyProcedure,
		svc.RemoveDependency,
		connect.WithSchema(stateServiceMethods.ByName("RemoveDependency")),
		connect.WithHandlerOptions(opts...),
	)
	stateServiceListDependenciesHandler := connect.NewUnaryHandler(
		StateServiceListDependenciesProcedure,
		svc.ListDependencies,
		connect.WithSchema(stateServiceMethods.ByName("ListDependencies")),
		connect.WithHandlerOptions(opts...),
	)
	stateServiceListDependentsHandler := connect.NewUnaryHandler(
		StateServiceListDependentsProcedure,
		svc.ListDependents,
		connect.WithSchema(stateServiceMethods.ByName("ListDependents")),
		connect.WithHandlerOptions(opts...),
	)
	stateServiceSearchByOutputHandler := connect.NewUnaryHandler(
		StateServiceSearchByOutputProcedure,
		svc.SearchByOutput,
		connect.WithSchema(stateServiceMethods.ByName("SearchByOutput")),
		connect.WithHandlerOptions(opts...),
	)
	stateServiceGetTopologicalOrderHandler := connect.NewUnaryHandler(
		StateServiceGetTopologicalOrderProcedure,
		svc.GetTopologicalOrder,
		connect.WithSchema(stateServiceMethods.ByName("GetTopologicalOrder")),
		connect.WithHandlerOptions(opts...),
	)
	stateServiceGetStateStatusHandler := connect.NewUnaryHandler(
		StateServiceGetStateStatusProcedure,
		svc.GetStateStatus,
		connect.WithSchema(stateServiceMethods.ByName("GetStateStatus")),
		connect.WithHandlerOptions(opts...),
	)
	stateServiceGetDependencyGraphHandler := connect.NewUnaryHandler(
		StateServiceGetDependencyGraphProcedure,
		svc.GetDependencyGraph,
		connect.WithSchema(stateServiceMethods.ByName("GetDependencyGraph")),
		connect.WithHandlerOptions(opts...),
	)
	stateServiceListStateOutputsHandler := connect.NewUnaryHandler(
		StateServiceListStateOutputsProcedure,
		svc.ListStateOutputs,
		connect.WithSchema(stateServiceMethods.ByName("ListStateOutputs")),
		connect.WithHandlerOptions(opts...),
	)
	stateServiceGetStateInfoHandler := connect.NewUnaryHandler(
		StateServiceGetStateInfoProcedure,
		svc.GetStateInfo,
		connect.WithSchema(stateServiceMethods.ByName("GetStateInfo")),
		connect.WithHandlerOptions(opts...),
	)
	stateServiceListAllEdgesHandler := connect.NewUnaryHandler(
		StateServiceListAllEdgesProcedure,
		svc.ListAllEdges,
		connect.WithSchema(stateServiceMethods.ByName("ListAllEdges")),
		connect.WithHandlerOptions(opts...),
	)
	stateServiceUpdateStateLabelsHandler := connect.NewUnaryHandler(
		StateServiceUpdateStateLabelsProcedure,
		svc.UpdateStateLabels,
		connect.WithSchema(stateServiceMethods.ByName("UpdateStateLabels")),
		connect.WithHandlerOptions(opts...),
	)
	stateServiceGetLabelPolicyHandler := connect.NewUnaryHandler(
		StateServiceGetLabelPolicyProcedure,
		svc.GetLabelPolicy,
		connect.WithSchema(stateServiceMethods.ByName("GetLabelPolicy")),
		connect.WithHandlerOptions(opts...),
	)
	stateServiceSetLabelPolicyHandler := connect.NewUnaryHandler(
		StateServiceSetLabelPolicyProcedure,
		svc.SetLabelPolicy,
		connect.WithSchema(stateServiceMethods.ByName("SetLabelPolicy")),
		connect.WithHandlerOptions(opts...),
	)
	stateServiceCreateServiceAccountHandler := connect.NewUnaryHandler(
		StateServiceCreateServiceAccountProcedure,
		svc.CreateServiceAccount,
		connect.WithSchema(stateServiceMethods.ByName("CreateServiceAccount")),
		connect.WithHandlerOptions(opts...),
	)
	stateServiceListServiceAccountsHandler := connect.NewUnaryHandler(
		StateServiceListServiceAccountsProcedure,
		svc.ListServiceAccounts,
		connect.WithSchema(stateServiceMethods.ByName("ListServiceAccounts")),
		connect.WithHandlerOptions(opts...),
	)
	stateServiceRevokeServiceAccountHandler := connect.NewUnaryHandler(
		StateServiceRevokeServiceAccountProcedure,
		svc.RevokeServiceAccount,
		connect.WithSchema(stateServiceMethods.ByName("RevokeServiceAccount")),
		connect.WithHandlerOptions(opts...),
	)
	stateServiceRotateServiceAccountHandler := connect.NewUnaryHandler(
		StateServiceRotateServiceAccountProcedure,
		svc.RotateServiceAccount,
		connect.WithSchema(stateServiceMethods.ByName("RotateServiceAccount")),
		connect.WithHandlerOptions(opts...),
	)
	stateServiceCreateRoleHandler := connect.NewUnaryHandler(
		StateServiceCreateRoleProcedure,
		svc.CreateRole,
		connect.WithSchema(stateServiceMethods.ByName("CreateRole")),
		connect.WithHandlerOptions(opts...),
	)
	stateServiceListRolesHandler := connect.NewUnaryHandler(
		StateServiceListRolesProcedure,
		svc.ListRoles,
		connect.WithSchema(stateServiceMethods.ByName("ListRoles")),
		connect.WithHandlerOptions(opts...),
	)
	stateServiceUpdateRoleHandler := connect.NewUnaryHandler(
		StateServiceUpdateRoleProcedure,
		svc.UpdateRole,
		connect.WithSchema(stateServiceMethods.ByName("UpdateRole")),
		connect.WithHandlerOptions(opts...),
	)
	stateServiceDeleteRoleHandler := connect.NewUnaryHandler(
		StateServiceDeleteRoleProcedure,
		svc.DeleteRole,
		connect.WithSchema(stateServiceMethods.ByName("DeleteRole")),
		connect.WithHandlerOptions(opts...),
	)
	stateServiceAssignRoleHandler := connect.NewUnaryHandler(
		StateServiceAssignRoleProcedure,
		svc.AssignRole,
		connect.WithSchema(stateServiceMethods.ByName("AssignRole")),
		connect.WithHandlerOptions(opts...),
	)
	stateServiceRemoveRoleHandler := connect.NewUnaryHandler(
		StateServiceRemoveRoleProcedure,
		svc.RemoveRole,
		connect.WithSchema(stateServiceMethods.ByName("RemoveRole")),
		connect.WithHandlerOptions(opts...),
	)
	stateServiceListUserRolesHandler := connect.NewUnaryHandler(
		StateServiceListUserRolesProcedure,
		svc.ListUserRoles,
		connect.WithSchema(stateServiceMethods.ByName("ListUserRoles")),
		connect.WithHandlerOptions(opts...),
	)
	stateServiceAssignGroupRoleHandler := connect.NewUnaryHandler(
		StateServiceAssignGroupRoleProcedure,
		svc.AssignGroupRole,
		connect.WithSchema(stateServiceMethods.ByName("AssignGroupRole")),
		connect.WithHandlerOptions(opts...),
	)
	stateServiceRemoveGroupRoleHandler := connect.NewUnaryHandler(
		StateServiceRemoveGroupRoleProcedure,
		svc.RemoveGroupRole,
		connect.WithSchema(stateServiceMethods.ByName("RemoveGroupRole")),
		connect.WithHandlerOptions(opts...),
	)
	stateServiceListGroupRolesHandler := connect.NewUnaryHandler(
		StateServiceListGroupRolesProcedure,
		svc.ListGroupRoles,
		connect.WithSchema(stateServiceMethods.ByName("ListGroupRoles")),
		connect.WithHandlerOptions(opts...),
	)
	stateServiceGetEffectivePermissionsHandler := connect.NewUnaryHandler(
		StateServiceGetEffectivePermissionsProcedure,
		svc.GetEffectivePermissions,
		connect.WithSchema(stateServiceMethods.ByName("GetEffectivePermissions")),
		connect.WithHandlerOptions(opts...),
	)
	stateServiceListSessionsHandler := connect.NewUnaryHandler(
		StateServiceListSessionsProcedure,
		svc.ListSessions,
		connect.WithSchema(stateServiceMethods.ByName("ListSessions")),
		connect.WithHandlerOptions(opts...),
	)
	stateServiceRevokeSessionHandler := connect.NewUnaryHandler(
		StateServiceRevokeSessionProcedure,
		svc.RevokeSession,
		connect.WithSchema(stateServiceMethods.ByName("RevokeSession")),
		connect.WithHandlerOptions(opts...),
	)
	stateServiceSetOutputSchemaHandler := connect.NewUnaryHandler(
		StateServiceSetOutputSchemaProcedure,
		svc.SetOutputSchema,
		connect.WithSchema(stateServiceMethods.ByName("SetOutputSchema")),
		connect.WithHandlerOptions(opts...),
	)
	stateServiceGetOutputSchemaHandler := connect.NewUnaryHandler(
		StateServiceGetOutputSchemaProcedure,
		svc.GetOutputSchema,
		connect.WithSchema(stateServiceMethods.ByName("GetOutputSchema")),
		connect.WithHandlerOptions(opts...),
	)
	return "/state.v1.StateService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case StateServiceCreateStateProcedure:
			stateServiceCreateStateHandler.ServeHTTP(w, r)
		case StateServiceListStatesProcedure:
			stateServiceListStatesHandler.ServeHTTP(w, r)
		case StateServiceGetStateConfigProcedure:
			stateServiceGetStateConfigHandler.ServeHTTP(w, r)
		case StateServiceGetStateLockProcedure:
			stateServiceGetStateLockHandler.ServeHTTP(w, r)
		case StateServiceUnlockStateProcedure:
			stateServiceUnlockStateHandler.ServeHTTP(w, r)
		case StateServiceAddDependencyProcedure:
			stateServiceAddDependencyHandler.ServeHTTP(w, r)
		case StateServiceRemoveDependencyProcedure:
			stateServiceRemoveDependencyHandler.ServeHTTP(w, r)
		case StateServiceListDependenciesProcedure:
			stateServiceListDependenciesHandler.ServeHTTP(w, r)
		case StateServiceListDependentsProcedure:
			stateServiceListDependentsHandler.ServeHTTP(w, r)
		case StateServiceSearchByOutputProcedure:
			stateServiceSearchByOutputHandler.ServeHTTP(w, r)
		case StateServiceGetTopologicalOrderProcedure:
			stateServiceGetTopologicalOrderHandler.ServeHTTP(w, r)
		case StateServiceGetStateStatusProcedure:
			stateServiceGetStateStatusHandler.ServeHTTP(w, r)
		case StateServiceGetDependencyGraphProcedure:
			stateServiceGetDependencyGraphHandler.ServeHTTP(w, r)
		case StateServiceListStateOutputsProcedure:
			stateServiceListStateOutputsHandler.ServeHTTP(w, r)
		case StateServiceGetStateInfoProcedure:
			stateServiceGetStateInfoHandler.ServeHTTP(w, r)
		case StateServiceListAllEdgesProcedure:
			stateServiceListAllEdgesHandler.ServeHTTP(w, r)
		case StateServiceUpdateStateLabelsProcedure:
			stateServiceUpdateStateLabelsHandler.ServeHTTP(w, r)
		case StateServiceGetLabelPolicyProcedure:
			stateServiceGetLabelPolicyHandler.ServeHTTP(w, r)
		case StateServiceSetLabelPolicyProcedure:
			stateServiceSetLabelPolicyHandler.ServeHTTP(w, r)
		case StateServiceCreateServiceAccountProcedure:
			stateServiceCreateServiceAccountHandler.ServeHTTP(w, r)
		case StateServiceListServiceAccountsProcedure:
			stateServiceListServiceAccountsHandler.ServeHTTP(w, r)
		case StateServiceRevokeServiceAccountProcedure:
			stateServiceRevokeServiceAccountHandler.ServeHTTP(w, r)
		case StateServiceRotateServiceAccountProcedure:
			stateServiceRotateServiceAccountHandler.ServeHTTP(w, r)
		case StateServiceCreateRoleProcedure:
			stateServiceCreateRoleHandler.ServeHTTP(w, r)
		case StateServiceListRolesProcedure:
			stateServiceListRolesHandler.ServeHTTP(w, r)
		case StateServiceUpdateRoleProcedure:
			stateServiceUpdateRoleHandler.ServeHTTP(w, r)
		case StateServiceDeleteRoleProcedure:
			stateServiceDeleteRoleHandler.ServeHTTP(w, r)
		case StateServiceAssignRoleProcedure:
			stateServiceAssignRoleHandler.ServeHTTP(w, r)
		case StateServiceRemoveRoleProcedure:
			stateServiceRemoveRoleHandler.ServeHTTP(w, r)
		case StateServiceListUserRolesProcedure:
			stateServiceListUserRolesHandler.ServeHTTP(w, r)
		case StateServiceAssignGroupRoleProcedure:
			stateServiceAssignGroupRoleHandler.ServeHTTP(w, r)
		case StateServiceRemoveGroupRoleProcedure:
			stateServiceRemoveGroupRoleHandler.ServeHTTP(w, r)
		case StateServiceListGroupRolesProcedure:
			stateServiceListGroupRolesHandler.ServeHTTP(w, r)
		case StateServiceGetEffectivePermissionsProcedure:
			stateServiceGetEffectivePermissionsHandler.ServeHTTP(w, r)
		case StateServiceListSessionsProcedure:
			stateServiceListSessionsHandler.ServeHTTP(w, r)
		case StateServiceRevokeSessionProcedure:
			stateServiceRevokeSessionHandler.ServeHTTP(w, r)
		case StateServiceSetOutputSchemaProcedure:
			stateServiceSetOutputSchemaHandler.ServeHTTP(w, r)
		case StateServiceGetOutputSchemaProcedure:
			stateServiceGetOutputSchemaHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedStateServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedStateServiceHandler struct{}

func (UnimplementedStateServiceHandler) CreateState(context.Context, *connect.Request[v1.CreateStateRequest]) (*connect.Response[v1.CreateStateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("state.v1.StateService.CreateState is not implemented"))
}

func (UnimplementedStateServiceHandler) ListStates(context.Context, *connect.Request[v1.ListStatesRequest]) (*connect.Response[v1.ListStatesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("state.v1.StateService.ListStates is not implemented"))
}

func (UnimplementedStateServiceHandler) GetStateConfig(context.Context, *connect.Request[v1.GetStateConfigRequest]) (*connect.Response[v1.GetStateConfigResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("state.v1.StateService.GetStateConfig is not implemented"))
}

func (UnimplementedStateServiceHandler) GetStateLock(context.Context, *connect.Request[v1.GetStateLockRequest]) (*connect.Response[v1.GetStateLockResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("state.v1.StateService.GetStateLock is not implemented"))
}

func (UnimplementedStateServiceHandler) UnlockState(context.Context, *connect.Request[v1.UnlockStateRequest]) (*connect.Response[v1.UnlockStateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("state.v1.StateService.UnlockState is not implemented"))
}

func (UnimplementedStateServiceHandler) AddDependency(context.Context, *connect.Request[v1.AddDependencyRequest]) (*connect.Response[v1.AddDependencyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("state.v1.StateService.AddDependency is not implemented"))
}

func (UnimplementedStateServiceHandler) RemoveDependency(context.Context, *connect.Request[v1.RemoveDependencyRequest]) (*connect.Response[v1.RemoveDependencyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("state.v1.StateService.RemoveDependency is not implemented"))
}

func (UnimplementedStateServiceHandler) ListDependencies(context.Context, *connect.Request[v1.ListDependenciesRequest]) (*connect.Response[v1.ListDependenciesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("state.v1.StateService.ListDependencies is not implemented"))
}

func (UnimplementedStateServiceHandler) ListDependents(context.Context, *connect.Request[v1.ListDependentsRequest]) (*connect.Response[v1.ListDependentsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("state.v1.StateService.ListDependents is not implemented"))
}

func (UnimplementedStateServiceHandler) SearchByOutput(context.Context, *connect.Request[v1.SearchByOutputRequest]) (*connect.Response[v1.SearchByOutputResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("state.v1.StateService.SearchByOutput is not implemented"))
}

func (UnimplementedStateServiceHandler) GetTopologicalOrder(context.Context, *connect.Request[v1.GetTopologicalOrderRequest]) (*connect.Response[v1.GetTopologicalOrderResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("state.v1.StateService.GetTopologicalOrder is not implemented"))
}

func (UnimplementedStateServiceHandler) GetStateStatus(context.Context, *connect.Request[v1.GetStateStatusRequest]) (*connect.Response[v1.GetStateStatusResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("state.v1.StateService.GetStateStatus is not implemented"))
}

func (UnimplementedStateServiceHandler) GetDependencyGraph(context.Context, *connect.Request[v1.GetDependencyGraphRequest]) (*connect.Response[v1.GetDependencyGraphResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("state.v1.StateService.GetDependencyGraph is not implemented"))
}

func (UnimplementedStateServiceHandler) ListStateOutputs(context.Context, *connect.Request[v1.ListStateOutputsRequest]) (*connect.Response[v1.ListStateOutputsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("state.v1.StateService.ListStateOutputs is not implemented"))
}

func (UnimplementedStateServiceHandler) GetStateInfo(context.Context, *connect.Request[v1.GetStateInfoRequest]) (*connect.Response[v1.GetStateInfoResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("state.v1.StateService.GetStateInfo is not implemented"))
}

func (UnimplementedStateServiceHandler) ListAllEdges(context.Context, *connect.Request[v1.ListAllEdgesRequest]) (*connect.Response[v1.ListAllEdgesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("state.v1.StateService.ListAllEdges is not implemented"))
}

func (UnimplementedStateServiceHandler) UpdateStateLabels(context.Context, *connect.Request[v1.UpdateStateLabelsRequest]) (*connect.Response[v1.UpdateStateLabelsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("state.v1.StateService.UpdateStateLabels is not implemented"))
}

func (UnimplementedStateServiceHandler) GetLabelPolicy(context.Context, *connect.Request[v1.GetLabelPolicyRequest]) (*connect.Response[v1.GetLabelPolicyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("state.v1.StateService.GetLabelPolicy is not implemented"))
}

func (UnimplementedStateServiceHandler) SetLabelPolicy(context.Context, *connect.Request[v1.SetLabelPolicyRequest]) (*connect.Response[v1.SetLabelPolicyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("state.v1.StateService.SetLabelPolicy is not implemented"))
}

func (UnimplementedStateServiceHandler) CreateServiceAccount(context.Context, *connect.Request[v1.CreateServiceAccountRequest]) (*connect.Response[v1.CreateServiceAccountResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("state.v1.StateService.CreateServiceAccount is not implemented"))
}

func (UnimplementedStateServiceHandler) ListServiceAccounts(context.Context, *connect.Request[v1.ListServiceAccountsRequest]) (*connect.Response[v1.ListServiceAccountsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("state.v1.StateService.ListServiceAccounts is not implemented"))
}

func (UnimplementedStateServiceHandler) RevokeServiceAccount(context.Context, *connect.Request[v1.RevokeServiceAccountRequest]) (*connect.Response[v1.RevokeServiceAccountResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("state.v1.StateService.RevokeServiceAccount is not implemented"))
}

func (UnimplementedStateServiceHandler) RotateServiceAccount(context.Context, *connect.Request[v1.RotateServiceAccountRequest]) (*connect.Response[v1.RotateServiceAccountResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("state.v1.StateService.RotateServiceAccount is not implemented"))
}

func (UnimplementedStateServiceHandler) CreateRole(context.Context, *connect.Request[v1.CreateRoleRequest]) (*connect.Response[v1.CreateRoleResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("state.v1.StateService.CreateRole is not implemented"))
}

func (UnimplementedStateServiceHandler) ListRoles(context.Context, *connect.Request[v1.ListRolesRequest]) (*connect.Response[v1.ListRolesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("state.v1.StateService.ListRoles is not implemented"))
}

func (UnimplementedStateServiceHandler) UpdateRole(context.Context, *connect.Request[v1.UpdateRoleRequest]) (*connect.Response[v1.UpdateRoleResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("state.v1.StateService.UpdateRole is not implemented"))
}

func (UnimplementedStateServiceHandler) DeleteRole(context.Context, *connect.Request[v1.DeleteRoleRequest]) (*connect.Response[v1.DeleteRoleResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("state.v1.StateService.DeleteRole is not implemented"))
}

func (UnimplementedStateServiceHandler) AssignRole(context.Context, *connect.Request[v1.AssignRoleRequest]) (*connect.Response[v1.AssignRoleResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("state.v1.StateService.AssignRole is not implemented"))
}

func (UnimplementedStateServiceHandler) RemoveRole(context.Context, *connect.Request[v1.RemoveRoleRequest]) (*connect.Response[v1.RemoveRoleResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("state.v1.StateService.RemoveRole is not implemented"))
}

func (UnimplementedStateServiceHandler) ListUserRoles(context.Context, *connect.Request[v1.ListUserRolesRequest]) (*connect.Response[v1.ListUserRolesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("state.v1.StateService.ListUserRoles is not implemented"))
}

func (UnimplementedStateServiceHandler) AssignGroupRole(context.Context, *connect.Request[v1.AssignGroupRoleRequest]) (*connect.Response[v1.AssignGroupRoleResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("state.v1.StateService.AssignGroupRole is not implemented"))
}

func (UnimplementedStateServiceHandler) RemoveGroupRole(context.Context, *connect.Request[v1.RemoveGroupRoleRequest]) (*connect.Response[v1.RemoveGroupRoleResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("state.v1.StateService.RemoveGroupRole is not implemented"))
}

func (UnimplementedStateServiceHandler) ListGroupRoles(context.Context, *connect.Request[v1.ListGroupRolesRequest]) (*connect.Response[v1.ListGroupRolesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("state.v1.StateService.ListGroupRoles is not implemented"))
}

func (UnimplementedStateServiceHandler) GetEffectivePermissions(context.Context, *connect.Request[v1.GetEffectivePermissionsRequest]) (*connect.Response[v1.GetEffectivePermissionsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("state.v1.StateService.GetEffectivePermissions is not implemented"))
}

func (UnimplementedStateServiceHandler) ListSessions(context.Context, *connect.Request[v1.ListSessionsRequest]) (*connect.Response[v1.ListSessionsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("state.v1.StateService.ListSessions is not implemented"))
}

func (UnimplementedStateServiceHandler) RevokeSession(context.Context, *connect.Request[v1.RevokeSessionRequest]) (*connect.Response[v1.RevokeSessionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("state.v1.StateService.RevokeSession is not implemented"))
}

func (UnimplementedStateServiceHandler) SetOutputSchema(context.Context, *connect.Request[v1.SetOutputSchemaRequest]) (*connect.Response[v1.SetOutputSchemaResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("state.v1.StateService.SetOutputSchema is not implemented"))
}

func (UnimplementedStateServiceHandler) GetOutputSchema(context.Context, *connect.Request[v1.GetOutputSchemaRequest]) (*connect.Response[v1.GetOutputSchemaResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("state.v1.StateService.GetOutputSchema is not implemented"))
}
