version: 2

before:
  hooks:
    # Install dependencies, build JS SDK, then build webapp bundle
    - bash -c "pnpm install --frozen-lockfile && cd js/sdk && pnpm run build && cd ../../webapp && pnpm run build"

builds:
  - id: gridapi
    main: ./cmd/gridapi
    binary: gridapi
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
      - -X main.builtBy=goreleaser
    env:
      - CGO_ENABLED=0

  - id: gridctl
    main: ./cmd/gridctl
    binary: gridctl
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
      - -X main.builtBy=goreleaser
    env:
      - CGO_ENABLED=0

archives:
  - id: gridapi
    ids:
      - gridapi
    allow_different_binary_count: true
    formats: [ tar.gz ]
    name_template: gridapi_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    files:
      - LICENSE
      - README.md

  - id: gridctl
    ids:
      - gridctl
    allow_different_binary_count: true
    formats: [ tar.gz ]
    name_template: gridctl_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    files:
      - LICENSE
      - README.md

  - id: webapp
    meta: true
    formats: [ tar.gz ]
    name_template: "webapp_{{ .Version }}"
    files:
      # Add index.html at root (strip webapp/dist parent)
      - src: webapp/dist/index.html
        strip_parent: true
      # Add all files from assets directory
      - src: webapp/dist/assets/*
        dst: assets

checksum:
  name_template: "checksums.txt"

changelog:
  use: github-native

release:
  github:
    owner: TerraConstructs
    name: grid
  draft: false
  prerelease: auto
