// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: state/v1/state.proto

package statev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CreateStateRequest creates a new state using a client-generated GUID.
type CreateStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Guid          string                 `protobuf:"bytes,1,opt,name=guid,proto3" json:"guid,omitempty"`
	LogicId       string                 `protobuf:"bytes,2,opt,name=logic_id,json=logicId,proto3" json:"logic_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateStateRequest) Reset() {
	*x = CreateStateRequest{}
	mi := &file_state_v1_state_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStateRequest) ProtoMessage() {}

func (x *CreateStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_state_v1_state_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStateRequest.ProtoReflect.Descriptor instead.
func (*CreateStateRequest) Descriptor() ([]byte, []int) {
	return file_state_v1_state_proto_rawDescGZIP(), []int{0}
}

func (x *CreateStateRequest) GetGuid() string {
	if x != nil {
		return x.Guid
	}
	return ""
}

func (x *CreateStateRequest) GetLogicId() string {
	if x != nil {
		return x.LogicId
	}
	return ""
}

// CreateStateResponse confirms creation and returns backend config.
type CreateStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Guid          string                 `protobuf:"bytes,1,opt,name=guid,proto3" json:"guid,omitempty"`
	LogicId       string                 `protobuf:"bytes,2,opt,name=logic_id,json=logicId,proto3" json:"logic_id,omitempty"`
	BackendConfig *BackendConfig         `protobuf:"bytes,3,opt,name=backend_config,json=backendConfig,proto3" json:"backend_config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateStateResponse) Reset() {
	*x = CreateStateResponse{}
	mi := &file_state_v1_state_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStateResponse) ProtoMessage() {}

func (x *CreateStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_state_v1_state_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStateResponse.ProtoReflect.Descriptor instead.
func (*CreateStateResponse) Descriptor() ([]byte, []int) {
	return file_state_v1_state_proto_rawDescGZIP(), []int{1}
}

func (x *CreateStateResponse) GetGuid() string {
	if x != nil {
		return x.Guid
	}
	return ""
}

func (x *CreateStateResponse) GetLogicId() string {
	if x != nil {
		return x.LogicId
	}
	return ""
}

func (x *CreateStateResponse) GetBackendConfig() *BackendConfig {
	if x != nil {
		return x.BackendConfig
	}
	return nil
}

// ListStatesRequest requests all states.
type ListStatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListStatesRequest) Reset() {
	*x = ListStatesRequest{}
	mi := &file_state_v1_state_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStatesRequest) ProtoMessage() {}

func (x *ListStatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_state_v1_state_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStatesRequest.ProtoReflect.Descriptor instead.
func (*ListStatesRequest) Descriptor() ([]byte, []int) {
	return file_state_v1_state_proto_rawDescGZIP(), []int{2}
}

// ListStatesResponse returns all states with basic info.
type ListStatesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	States        []*StateInfo           `protobuf:"bytes,1,rep,name=states,proto3" json:"states,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListStatesResponse) Reset() {
	*x = ListStatesResponse{}
	mi := &file_state_v1_state_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStatesResponse) ProtoMessage() {}

func (x *ListStatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_state_v1_state_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStatesResponse.ProtoReflect.Descriptor instead.
func (*ListStatesResponse) Descriptor() ([]byte, []int) {
	return file_state_v1_state_proto_rawDescGZIP(), []int{3}
}

func (x *ListStatesResponse) GetStates() []*StateInfo {
	if x != nil {
		return x.States
	}
	return nil
}

// StateInfo is summary information for a state.
type StateInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Guid          string                 `protobuf:"bytes,1,opt,name=guid,proto3" json:"guid,omitempty"`
	LogicId       string                 `protobuf:"bytes,2,opt,name=logic_id,json=logicId,proto3" json:"logic_id,omitempty"`
	Locked        bool                   `protobuf:"varint,3,opt,name=locked,proto3" json:"locked,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	SizeBytes     int64                  `protobuf:"varint,6,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateInfo) Reset() {
	*x = StateInfo{}
	mi := &file_state_v1_state_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateInfo) ProtoMessage() {}

func (x *StateInfo) ProtoReflect() protoreflect.Message {
	mi := &file_state_v1_state_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateInfo.ProtoReflect.Descriptor instead.
func (*StateInfo) Descriptor() ([]byte, []int) {
	return file_state_v1_state_proto_rawDescGZIP(), []int{4}
}

func (x *StateInfo) GetGuid() string {
	if x != nil {
		return x.Guid
	}
	return ""
}

func (x *StateInfo) GetLogicId() string {
	if x != nil {
		return x.LogicId
	}
	return ""
}

func (x *StateInfo) GetLocked() bool {
	if x != nil {
		return x.Locked
	}
	return false
}

func (x *StateInfo) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *StateInfo) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *StateInfo) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

// BackendConfig contains Terraform backend configuration URLs.
type BackendConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	LockAddress   string                 `protobuf:"bytes,2,opt,name=lock_address,json=lockAddress,proto3" json:"lock_address,omitempty"`
	UnlockAddress string                 `protobuf:"bytes,3,opt,name=unlock_address,json=unlockAddress,proto3" json:"unlock_address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackendConfig) Reset() {
	*x = BackendConfig{}
	mi := &file_state_v1_state_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackendConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackendConfig) ProtoMessage() {}

func (x *BackendConfig) ProtoReflect() protoreflect.Message {
	mi := &file_state_v1_state_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackendConfig.ProtoReflect.Descriptor instead.
func (*BackendConfig) Descriptor() ([]byte, []int) {
	return file_state_v1_state_proto_rawDescGZIP(), []int{5}
}

func (x *BackendConfig) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *BackendConfig) GetLockAddress() string {
	if x != nil {
		return x.LockAddress
	}
	return ""
}

func (x *BackendConfig) GetUnlockAddress() string {
	if x != nil {
		return x.UnlockAddress
	}
	return ""
}

// GetStateConfigRequest retrieves backend config for existing state.
type GetStateConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LogicId       string                 `protobuf:"bytes,1,opt,name=logic_id,json=logicId,proto3" json:"logic_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStateConfigRequest) Reset() {
	*x = GetStateConfigRequest{}
	mi := &file_state_v1_state_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStateConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStateConfigRequest) ProtoMessage() {}

func (x *GetStateConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_state_v1_state_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStateConfigRequest.ProtoReflect.Descriptor instead.
func (*GetStateConfigRequest) Descriptor() ([]byte, []int) {
	return file_state_v1_state_proto_rawDescGZIP(), []int{6}
}

func (x *GetStateConfigRequest) GetLogicId() string {
	if x != nil {
		return x.LogicId
	}
	return ""
}

// GetStateConfigResponse returns backend config.
type GetStateConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Guid          string                 `protobuf:"bytes,1,opt,name=guid,proto3" json:"guid,omitempty"`
	BackendConfig *BackendConfig         `protobuf:"bytes,2,opt,name=backend_config,json=backendConfig,proto3" json:"backend_config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStateConfigResponse) Reset() {
	*x = GetStateConfigResponse{}
	mi := &file_state_v1_state_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStateConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStateConfigResponse) ProtoMessage() {}

func (x *GetStateConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_state_v1_state_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStateConfigResponse.ProtoReflect.Descriptor instead.
func (*GetStateConfigResponse) Descriptor() ([]byte, []int) {
	return file_state_v1_state_proto_rawDescGZIP(), []int{7}
}

func (x *GetStateConfigResponse) GetGuid() string {
	if x != nil {
		return x.Guid
	}
	return ""
}

func (x *GetStateConfigResponse) GetBackendConfig() *BackendConfig {
	if x != nil {
		return x.BackendConfig
	}
	return nil
}

// GetStateLockRequest fetches current lock metadata by GUID.
type GetStateLockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Guid          string                 `protobuf:"bytes,1,opt,name=guid,proto3" json:"guid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStateLockRequest) Reset() {
	*x = GetStateLockRequest{}
	mi := &file_state_v1_state_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStateLockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStateLockRequest) ProtoMessage() {}

func (x *GetStateLockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_state_v1_state_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStateLockRequest.ProtoReflect.Descriptor instead.
func (*GetStateLockRequest) Descriptor() ([]byte, []int) {
	return file_state_v1_state_proto_rawDescGZIP(), []int{8}
}

func (x *GetStateLockRequest) GetGuid() string {
	if x != nil {
		return x.Guid
	}
	return ""
}

// LockInfo mirrors Terraform's lock payload.
type LockInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Operation     string                 `protobuf:"bytes,2,opt,name=operation,proto3" json:"operation,omitempty"`
	Info          string                 `protobuf:"bytes,3,opt,name=info,proto3" json:"info,omitempty"`
	Who           string                 `protobuf:"bytes,4,opt,name=who,proto3" json:"who,omitempty"`
	Version       string                 `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	Created       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created,proto3" json:"created,omitempty"`
	Path          string                 `protobuf:"bytes,7,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LockInfo) Reset() {
	*x = LockInfo{}
	mi := &file_state_v1_state_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockInfo) ProtoMessage() {}

func (x *LockInfo) ProtoReflect() protoreflect.Message {
	mi := &file_state_v1_state_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockInfo.ProtoReflect.Descriptor instead.
func (*LockInfo) Descriptor() ([]byte, []int) {
	return file_state_v1_state_proto_rawDescGZIP(), []int{9}
}

func (x *LockInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LockInfo) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *LockInfo) GetInfo() string {
	if x != nil {
		return x.Info
	}
	return ""
}

func (x *LockInfo) GetWho() string {
	if x != nil {
		return x.Who
	}
	return ""
}

func (x *LockInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *LockInfo) GetCreated() *timestamppb.Timestamp {
	if x != nil {
		return x.Created
	}
	return nil
}

func (x *LockInfo) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

// StateLock response wrapper indicating lock state plus metadata when present.
type StateLock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Locked        bool                   `protobuf:"varint,1,opt,name=locked,proto3" json:"locked,omitempty"`
	Info          *LockInfo              `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateLock) Reset() {
	*x = StateLock{}
	mi := &file_state_v1_state_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateLock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateLock) ProtoMessage() {}

func (x *StateLock) ProtoReflect() protoreflect.Message {
	mi := &file_state_v1_state_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateLock.ProtoReflect.Descriptor instead.
func (*StateLock) Descriptor() ([]byte, []int) {
	return file_state_v1_state_proto_rawDescGZIP(), []int{10}
}

func (x *StateLock) GetLocked() bool {
	if x != nil {
		return x.Locked
	}
	return false
}

func (x *StateLock) GetInfo() *LockInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

// GetStateLockResponse returns current lock status.
type GetStateLockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lock          *StateLock             `protobuf:"bytes,1,opt,name=lock,proto3" json:"lock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStateLockResponse) Reset() {
	*x = GetStateLockResponse{}
	mi := &file_state_v1_state_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStateLockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStateLockResponse) ProtoMessage() {}

func (x *GetStateLockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_state_v1_state_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStateLockResponse.ProtoReflect.Descriptor instead.
func (*GetStateLockResponse) Descriptor() ([]byte, []int) {
	return file_state_v1_state_proto_rawDescGZIP(), []int{11}
}

func (x *GetStateLockResponse) GetLock() *StateLock {
	if x != nil {
		return x.Lock
	}
	return nil
}

// UnlockStateRequest releases a lock given the current lock ID.
type UnlockStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Guid          string                 `protobuf:"bytes,1,opt,name=guid,proto3" json:"guid,omitempty"`
	LockId        string                 `protobuf:"bytes,2,opt,name=lock_id,json=lockId,proto3" json:"lock_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlockStateRequest) Reset() {
	*x = UnlockStateRequest{}
	mi := &file_state_v1_state_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlockStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlockStateRequest) ProtoMessage() {}

func (x *UnlockStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_state_v1_state_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlockStateRequest.ProtoReflect.Descriptor instead.
func (*UnlockStateRequest) Descriptor() ([]byte, []int) {
	return file_state_v1_state_proto_rawDescGZIP(), []int{12}
}

func (x *UnlockStateRequest) GetGuid() string {
	if x != nil {
		return x.Guid
	}
	return ""
}

func (x *UnlockStateRequest) GetLockId() string {
	if x != nil {
		return x.LockId
	}
	return ""
}

// UnlockStateResponse mirrors GetStateLockResponse after unlock attempt.
type UnlockStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lock          *StateLock             `protobuf:"bytes,1,opt,name=lock,proto3" json:"lock,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlockStateResponse) Reset() {
	*x = UnlockStateResponse{}
	mi := &file_state_v1_state_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlockStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlockStateResponse) ProtoMessage() {}

func (x *UnlockStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_state_v1_state_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlockStateResponse.ProtoReflect.Descriptor instead.
func (*UnlockStateResponse) Descriptor() ([]byte, []int) {
	return file_state_v1_state_proto_rawDescGZIP(), []int{13}
}

func (x *UnlockStateResponse) GetLock() *StateLock {
	if x != nil {
		return x.Lock
	}
	return nil
}

var File_state_v1_state_proto protoreflect.FileDescriptor

const file_state_v1_state_proto_rawDesc = "" +
	"\n" +
	"\x14state/v1/state.proto\x12\bstate.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"C\n" +
	"\x12CreateStateRequest\x12\x12\n" +
	"\x04guid\x18\x01 \x01(\tR\x04guid\x12\x19\n" +
	"\blogic_id\x18\x02 \x01(\tR\alogicId\"\x84\x01\n" +
	"\x13CreateStateResponse\x12\x12\n" +
	"\x04guid\x18\x01 \x01(\tR\x04guid\x12\x19\n" +
	"\blogic_id\x18\x02 \x01(\tR\alogicId\x12>\n" +
	"\x0ebackend_config\x18\x03 \x01(\v2\x17.state.v1.BackendConfigR\rbackendConfig\"\x13\n" +
	"\x11ListStatesRequest\"A\n" +
	"\x12ListStatesResponse\x12+\n" +
	"\x06states\x18\x01 \x03(\v2\x13.state.v1.StateInfoR\x06states\"\xe7\x01\n" +
	"\tStateInfo\x12\x12\n" +
	"\x04guid\x18\x01 \x01(\tR\x04guid\x12\x19\n" +
	"\blogic_id\x18\x02 \x01(\tR\alogicId\x12\x16\n" +
	"\x06locked\x18\x03 \x01(\bR\x06locked\x129\n" +
	"\n" +
	"created_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x06 \x01(\x03R\tsizeBytes\"s\n" +
	"\rBackendConfig\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12!\n" +
	"\flock_address\x18\x02 \x01(\tR\vlockAddress\x12%\n" +
	"\x0eunlock_address\x18\x03 \x01(\tR\runlockAddress\"2\n" +
	"\x15GetStateConfigRequest\x12\x19\n" +
	"\blogic_id\x18\x01 \x01(\tR\alogicId\"l\n" +
	"\x16GetStateConfigResponse\x12\x12\n" +
	"\x04guid\x18\x01 \x01(\tR\x04guid\x12>\n" +
	"\x0ebackend_config\x18\x02 \x01(\v2\x17.state.v1.BackendConfigR\rbackendConfig\")\n" +
	"\x13GetStateLockRequest\x12\x12\n" +
	"\x04guid\x18\x01 \x01(\tR\x04guid\"\xc2\x01\n" +
	"\bLockInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1c\n" +
	"\toperation\x18\x02 \x01(\tR\toperation\x12\x12\n" +
	"\x04info\x18\x03 \x01(\tR\x04info\x12\x10\n" +
	"\x03who\x18\x04 \x01(\tR\x03who\x12\x18\n" +
	"\aversion\x18\x05 \x01(\tR\aversion\x124\n" +
	"\acreated\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\acreated\x12\x12\n" +
	"\x04path\x18\a \x01(\tR\x04path\"K\n" +
	"\tStateLock\x12\x16\n" +
	"\x06locked\x18\x01 \x01(\bR\x06locked\x12&\n" +
	"\x04info\x18\x02 \x01(\v2\x12.state.v1.LockInfoR\x04info\"?\n" +
	"\x14GetStateLockResponse\x12'\n" +
	"\x04lock\x18\x01 \x01(\v2\x13.state.v1.StateLockR\x04lock\"A\n" +
	"\x12UnlockStateRequest\x12\x12\n" +
	"\x04guid\x18\x01 \x01(\tR\x04guid\x12\x17\n" +
	"\alock_id\x18\x02 \x01(\tR\x06lockId\">\n" +
	"\x13UnlockStateResponse\x12'\n" +
	"\x04lock\x18\x01 \x01(\v2\x13.state.v1.StateLockR\x04lock2\x93\x03\n" +
	"\fStateService\x12J\n" +
	"\vCreateState\x12\x1c.state.v1.CreateStateRequest\x1a\x1d.state.v1.CreateStateResponse\x12G\n" +
	"\n" +
	"ListStates\x12\x1b.state.v1.ListStatesRequest\x1a\x1c.state.v1.ListStatesResponse\x12S\n" +
	"\x0eGetStateConfig\x12\x1f.state.v1.GetStateConfigRequest\x1a .state.v1.GetStateConfigResponse\x12M\n" +
	"\fGetStateLock\x12\x1d.state.v1.GetStateLockRequest\x1a\x1e.state.v1.GetStateLockResponse\x12J\n" +
	"\vUnlockState\x12\x1c.state.v1.UnlockStateRequest\x1a\x1d.state.v1.UnlockStateResponseB6Z4github.com/terraconstructs/grid/api/state/v1;statev1b\x06proto3"

var (
	file_state_v1_state_proto_rawDescOnce sync.Once
	file_state_v1_state_proto_rawDescData []byte
)

func file_state_v1_state_proto_rawDescGZIP() []byte {
	file_state_v1_state_proto_rawDescOnce.Do(func() {
		file_state_v1_state_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_state_v1_state_proto_rawDesc), len(file_state_v1_state_proto_rawDesc)))
	})
	return file_state_v1_state_proto_rawDescData
}

var file_state_v1_state_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_state_v1_state_proto_goTypes = []any{
	(*CreateStateRequest)(nil),     // 0: state.v1.CreateStateRequest
	(*CreateStateResponse)(nil),    // 1: state.v1.CreateStateResponse
	(*ListStatesRequest)(nil),      // 2: state.v1.ListStatesRequest
	(*ListStatesResponse)(nil),     // 3: state.v1.ListStatesResponse
	(*StateInfo)(nil),              // 4: state.v1.StateInfo
	(*BackendConfig)(nil),          // 5: state.v1.BackendConfig
	(*GetStateConfigRequest)(nil),  // 6: state.v1.GetStateConfigRequest
	(*GetStateConfigResponse)(nil), // 7: state.v1.GetStateConfigResponse
	(*GetStateLockRequest)(nil),    // 8: state.v1.GetStateLockRequest
	(*LockInfo)(nil),               // 9: state.v1.LockInfo
	(*StateLock)(nil),              // 10: state.v1.StateLock
	(*GetStateLockResponse)(nil),   // 11: state.v1.GetStateLockResponse
	(*UnlockStateRequest)(nil),     // 12: state.v1.UnlockStateRequest
	(*UnlockStateResponse)(nil),    // 13: state.v1.UnlockStateResponse
	(*timestamppb.Timestamp)(nil),  // 14: google.protobuf.Timestamp
}
var file_state_v1_state_proto_depIdxs = []int32{
	5,  // 0: state.v1.CreateStateResponse.backend_config:type_name -> state.v1.BackendConfig
	4,  // 1: state.v1.ListStatesResponse.states:type_name -> state.v1.StateInfo
	14, // 2: state.v1.StateInfo.created_at:type_name -> google.protobuf.Timestamp
	14, // 3: state.v1.StateInfo.updated_at:type_name -> google.protobuf.Timestamp
	5,  // 4: state.v1.GetStateConfigResponse.backend_config:type_name -> state.v1.BackendConfig
	14, // 5: state.v1.LockInfo.created:type_name -> google.protobuf.Timestamp
	9,  // 6: state.v1.StateLock.info:type_name -> state.v1.LockInfo
	10, // 7: state.v1.GetStateLockResponse.lock:type_name -> state.v1.StateLock
	10, // 8: state.v1.UnlockStateResponse.lock:type_name -> state.v1.StateLock
	0,  // 9: state.v1.StateService.CreateState:input_type -> state.v1.CreateStateRequest
	2,  // 10: state.v1.StateService.ListStates:input_type -> state.v1.ListStatesRequest
	6,  // 11: state.v1.StateService.GetStateConfig:input_type -> state.v1.GetStateConfigRequest
	8,  // 12: state.v1.StateService.GetStateLock:input_type -> state.v1.GetStateLockRequest
	12, // 13: state.v1.StateService.UnlockState:input_type -> state.v1.UnlockStateRequest
	1,  // 14: state.v1.StateService.CreateState:output_type -> state.v1.CreateStateResponse
	3,  // 15: state.v1.StateService.ListStates:output_type -> state.v1.ListStatesResponse
	7,  // 16: state.v1.StateService.GetStateConfig:output_type -> state.v1.GetStateConfigResponse
	11, // 17: state.v1.StateService.GetStateLock:output_type -> state.v1.GetStateLockResponse
	13, // 18: state.v1.StateService.UnlockState:output_type -> state.v1.UnlockStateResponse
	14, // [14:19] is the sub-list for method output_type
	9,  // [9:14] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_state_v1_state_proto_init() }
func file_state_v1_state_proto_init() {
	if File_state_v1_state_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_state_v1_state_proto_rawDesc), len(file_state_v1_state_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_state_v1_state_proto_goTypes,
		DependencyIndexes: file_state_v1_state_proto_depIdxs,
		MessageInfos:      file_state_v1_state_proto_msgTypes,
	}.Build()
	File_state_v1_state_proto = out.File
	file_state_v1_state_proto_goTypes = nil
	file_state_v1_state_proto_depIdxs = nil
}
