// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: state/v1/state.proto

package statev1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/terraconstructs/grid/api/state/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// StateServiceName is the fully-qualified name of the StateService service.
	StateServiceName = "state.v1.StateService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// StateServiceCreateStateProcedure is the fully-qualified name of the StateService's CreateState
	// RPC.
	StateServiceCreateStateProcedure = "/state.v1.StateService/CreateState"
	// StateServiceListStatesProcedure is the fully-qualified name of the StateService's ListStates RPC.
	StateServiceListStatesProcedure = "/state.v1.StateService/ListStates"
	// StateServiceGetStateConfigProcedure is the fully-qualified name of the StateService's
	// GetStateConfig RPC.
	StateServiceGetStateConfigProcedure = "/state.v1.StateService/GetStateConfig"
	// StateServiceGetStateLockProcedure is the fully-qualified name of the StateService's GetStateLock
	// RPC.
	StateServiceGetStateLockProcedure = "/state.v1.StateService/GetStateLock"
	// StateServiceUnlockStateProcedure is the fully-qualified name of the StateService's UnlockState
	// RPC.
	StateServiceUnlockStateProcedure = "/state.v1.StateService/UnlockState"
)

// StateServiceClient is a client for the state.v1.StateService service.
type StateServiceClient interface {
	// CreateState creates a new state with client-generated GUID and logic ID.
	CreateState(context.Context, *connect.Request[v1.CreateStateRequest]) (*connect.Response[v1.CreateStateResponse], error)
	// ListStates returns all states with summary information.
	ListStates(context.Context, *connect.Request[v1.ListStatesRequest]) (*connect.Response[v1.ListStatesResponse], error)
	// GetStateConfig retrieves backend configuration for an existing state by logic ID.
	GetStateConfig(context.Context, *connect.Request[v1.GetStateConfigRequest]) (*connect.Response[v1.GetStateConfigResponse], error)
	// GetStateLock inspects the current lock metadata for a state by GUID.
	GetStateLock(context.Context, *connect.Request[v1.GetStateLockRequest]) (*connect.Response[v1.GetStateLockResponse], error)
	// UnlockState releases a lock using the lock ID provided by Terraform/OpenTofu.
	UnlockState(context.Context, *connect.Request[v1.UnlockStateRequest]) (*connect.Response[v1.UnlockStateResponse], error)
}

// NewStateServiceClient constructs a client for the state.v1.StateService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewStateServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) StateServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	stateServiceMethods := v1.File_state_v1_state_proto.Services().ByName("StateService").Methods()
	return &stateServiceClient{
		createState: connect.NewClient[v1.CreateStateRequest, v1.CreateStateResponse](
			httpClient,
			baseURL+StateServiceCreateStateProcedure,
			connect.WithSchema(stateServiceMethods.ByName("CreateState")),
			connect.WithClientOptions(opts...),
		),
		listStates: connect.NewClient[v1.ListStatesRequest, v1.ListStatesResponse](
			httpClient,
			baseURL+StateServiceListStatesProcedure,
			connect.WithSchema(stateServiceMethods.ByName("ListStates")),
			connect.WithClientOptions(opts...),
		),
		getStateConfig: connect.NewClient[v1.GetStateConfigRequest, v1.GetStateConfigResponse](
			httpClient,
			baseURL+StateServiceGetStateConfigProcedure,
			connect.WithSchema(stateServiceMethods.ByName("GetStateConfig")),
			connect.WithClientOptions(opts...),
		),
		getStateLock: connect.NewClient[v1.GetStateLockRequest, v1.GetStateLockResponse](
			httpClient,
			baseURL+StateServiceGetStateLockProcedure,
			connect.WithSchema(stateServiceMethods.ByName("GetStateLock")),
			connect.WithClientOptions(opts...),
		),
		unlockState: connect.NewClient[v1.UnlockStateRequest, v1.UnlockStateResponse](
			httpClient,
			baseURL+StateServiceUnlockStateProcedure,
			connect.WithSchema(stateServiceMethods.ByName("UnlockState")),
			connect.WithClientOptions(opts...),
		),
	}
}

// stateServiceClient implements StateServiceClient.
type stateServiceClient struct {
	createState    *connect.Client[v1.CreateStateRequest, v1.CreateStateResponse]
	listStates     *connect.Client[v1.ListStatesRequest, v1.ListStatesResponse]
	getStateConfig *connect.Client[v1.GetStateConfigRequest, v1.GetStateConfigResponse]
	getStateLock   *connect.Client[v1.GetStateLockRequest, v1.GetStateLockResponse]
	unlockState    *connect.Client[v1.UnlockStateRequest, v1.UnlockStateResponse]
}

// CreateState calls state.v1.StateService.CreateState.
func (c *stateServiceClient) CreateState(ctx context.Context, req *connect.Request[v1.CreateStateRequest]) (*connect.Response[v1.CreateStateResponse], error) {
	return c.createState.CallUnary(ctx, req)
}

// ListStates calls state.v1.StateService.ListStates.
func (c *stateServiceClient) ListStates(ctx context.Context, req *connect.Request[v1.ListStatesRequest]) (*connect.Response[v1.ListStatesResponse], error) {
	return c.listStates.CallUnary(ctx, req)
}

// GetStateConfig calls state.v1.StateService.GetStateConfig.
func (c *stateServiceClient) GetStateConfig(ctx context.Context, req *connect.Request[v1.GetStateConfigRequest]) (*connect.Response[v1.GetStateConfigResponse], error) {
	return c.getStateConfig.CallUnary(ctx, req)
}

// GetStateLock calls state.v1.StateService.GetStateLock.
func (c *stateServiceClient) GetStateLock(ctx context.Context, req *connect.Request[v1.GetStateLockRequest]) (*connect.Response[v1.GetStateLockResponse], error) {
	return c.getStateLock.CallUnary(ctx, req)
}

// UnlockState calls state.v1.StateService.UnlockState.
func (c *stateServiceClient) UnlockState(ctx context.Context, req *connect.Request[v1.UnlockStateRequest]) (*connect.Response[v1.UnlockStateResponse], error) {
	return c.unlockState.CallUnary(ctx, req)
}

// StateServiceHandler is an implementation of the state.v1.StateService service.
type StateServiceHandler interface {
	// CreateState creates a new state with client-generated GUID and logic ID.
	CreateState(context.Context, *connect.Request[v1.CreateStateRequest]) (*connect.Response[v1.CreateStateResponse], error)
	// ListStates returns all states with summary information.
	ListStates(context.Context, *connect.Request[v1.ListStatesRequest]) (*connect.Response[v1.ListStatesResponse], error)
	// GetStateConfig retrieves backend configuration for an existing state by logic ID.
	GetStateConfig(context.Context, *connect.Request[v1.GetStateConfigRequest]) (*connect.Response[v1.GetStateConfigResponse], error)
	// GetStateLock inspects the current lock metadata for a state by GUID.
	GetStateLock(context.Context, *connect.Request[v1.GetStateLockRequest]) (*connect.Response[v1.GetStateLockResponse], error)
	// UnlockState releases a lock using the lock ID provided by Terraform/OpenTofu.
	UnlockState(context.Context, *connect.Request[v1.UnlockStateRequest]) (*connect.Response[v1.UnlockStateResponse], error)
}

// NewStateServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewStateServiceHandler(svc StateServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	stateServiceMethods := v1.File_state_v1_state_proto.Services().ByName("StateService").Methods()
	stateServiceCreateStateHandler := connect.NewUnaryHandler(
		StateServiceCreateStateProcedure,
		svc.CreateState,
		connect.WithSchema(stateServiceMethods.ByName("CreateState")),
		connect.WithHandlerOptions(opts...),
	)
	stateServiceListStatesHandler := connect.NewUnaryHandler(
		StateServiceListStatesProcedure,
		svc.ListStates,
		connect.WithSchema(stateServiceMethods.ByName("ListStates")),
		connect.WithHandlerOptions(opts...),
	)
	stateServiceGetStateConfigHandler := connect.NewUnaryHandler(
		StateServiceGetStateConfigProcedure,
		svc.GetStateConfig,
		connect.WithSchema(stateServiceMethods.ByName("GetStateConfig")),
		connect.WithHandlerOptions(opts...),
	)
	stateServiceGetStateLockHandler := connect.NewUnaryHandler(
		StateServiceGetStateLockProcedure,
		svc.GetStateLock,
		connect.WithSchema(stateServiceMethods.ByName("GetStateLock")),
		connect.WithHandlerOptions(opts...),
	)
	stateServiceUnlockStateHandler := connect.NewUnaryHandler(
		StateServiceUnlockStateProcedure,
		svc.UnlockState,
		connect.WithSchema(stateServiceMethods.ByName("UnlockState")),
		connect.WithHandlerOptions(opts...),
	)
	return "/state.v1.StateService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case StateServiceCreateStateProcedure:
			stateServiceCreateStateHandler.ServeHTTP(w, r)
		case StateServiceListStatesProcedure:
			stateServiceListStatesHandler.ServeHTTP(w, r)
		case StateServiceGetStateConfigProcedure:
			stateServiceGetStateConfigHandler.ServeHTTP(w, r)
		case StateServiceGetStateLockProcedure:
			stateServiceGetStateLockHandler.ServeHTTP(w, r)
		case StateServiceUnlockStateProcedure:
			stateServiceUnlockStateHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedStateServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedStateServiceHandler struct{}

func (UnimplementedStateServiceHandler) CreateState(context.Context, *connect.Request[v1.CreateStateRequest]) (*connect.Response[v1.CreateStateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("state.v1.StateService.CreateState is not implemented"))
}

func (UnimplementedStateServiceHandler) ListStates(context.Context, *connect.Request[v1.ListStatesRequest]) (*connect.Response[v1.ListStatesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("state.v1.StateService.ListStates is not implemented"))
}

func (UnimplementedStateServiceHandler) GetStateConfig(context.Context, *connect.Request[v1.GetStateConfigRequest]) (*connect.Response[v1.GetStateConfigResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("state.v1.StateService.GetStateConfig is not implemented"))
}

func (UnimplementedStateServiceHandler) GetStateLock(context.Context, *connect.Request[v1.GetStateLockRequest]) (*connect.Response[v1.GetStateLockResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("state.v1.StateService.GetStateLock is not implemented"))
}

func (UnimplementedStateServiceHandler) UnlockState(context.Context, *connect.Request[v1.UnlockStateRequest]) (*connect.Response[v1.UnlockStateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("state.v1.StateService.UnlockState is not implemented"))
}
