// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: state/v1/state.proto

package statev1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/terraconstructs/grid/api/state/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// StateServiceName is the fully-qualified name of the StateService service.
	StateServiceName = "state.v1.StateService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// StateServiceCreateStateProcedure is the fully-qualified name of the StateService's CreateState
	// RPC.
	StateServiceCreateStateProcedure = "/state.v1.StateService/CreateState"
	// StateServiceListStatesProcedure is the fully-qualified name of the StateService's ListStates RPC.
	StateServiceListStatesProcedure = "/state.v1.StateService/ListStates"
	// StateServiceGetStateConfigProcedure is the fully-qualified name of the StateService's
	// GetStateConfig RPC.
	StateServiceGetStateConfigProcedure = "/state.v1.StateService/GetStateConfig"
	// StateServiceGetStateLockProcedure is the fully-qualified name of the StateService's GetStateLock
	// RPC.
	StateServiceGetStateLockProcedure = "/state.v1.StateService/GetStateLock"
	// StateServiceUnlockStateProcedure is the fully-qualified name of the StateService's UnlockState
	// RPC.
	StateServiceUnlockStateProcedure = "/state.v1.StateService/UnlockState"
	// StateServiceAddDependencyProcedure is the fully-qualified name of the StateService's
	// AddDependency RPC.
	StateServiceAddDependencyProcedure = "/state.v1.StateService/AddDependency"
	// StateServiceRemoveDependencyProcedure is the fully-qualified name of the StateService's
	// RemoveDependency RPC.
	StateServiceRemoveDependencyProcedure = "/state.v1.StateService/RemoveDependency"
	// StateServiceListDependenciesProcedure is the fully-qualified name of the StateService's
	// ListDependencies RPC.
	StateServiceListDependenciesProcedure = "/state.v1.StateService/ListDependencies"
	// StateServiceListDependentsProcedure is the fully-qualified name of the StateService's
	// ListDependents RPC.
	StateServiceListDependentsProcedure = "/state.v1.StateService/ListDependents"
	// StateServiceSearchByOutputProcedure is the fully-qualified name of the StateService's
	// SearchByOutput RPC.
	StateServiceSearchByOutputProcedure = "/state.v1.StateService/SearchByOutput"
	// StateServiceGetTopologicalOrderProcedure is the fully-qualified name of the StateService's
	// GetTopologicalOrder RPC.
	StateServiceGetTopologicalOrderProcedure = "/state.v1.StateService/GetTopologicalOrder"
	// StateServiceGetStateStatusProcedure is the fully-qualified name of the StateService's
	// GetStateStatus RPC.
	StateServiceGetStateStatusProcedure = "/state.v1.StateService/GetStateStatus"
	// StateServiceGetDependencyGraphProcedure is the fully-qualified name of the StateService's
	// GetDependencyGraph RPC.
	StateServiceGetDependencyGraphProcedure = "/state.v1.StateService/GetDependencyGraph"
	// StateServiceListStateOutputsProcedure is the fully-qualified name of the StateService's
	// ListStateOutputs RPC.
	StateServiceListStateOutputsProcedure = "/state.v1.StateService/ListStateOutputs"
	// StateServiceGetStateInfoProcedure is the fully-qualified name of the StateService's GetStateInfo
	// RPC.
	StateServiceGetStateInfoProcedure = "/state.v1.StateService/GetStateInfo"
)

// StateServiceClient is a client for the state.v1.StateService service.
type StateServiceClient interface {
	// CreateState creates a new state with client-generated GUID and logic ID.
	CreateState(context.Context, *connect.Request[v1.CreateStateRequest]) (*connect.Response[v1.CreateStateResponse], error)
	// ListStates returns all states with summary information.
	ListStates(context.Context, *connect.Request[v1.ListStatesRequest]) (*connect.Response[v1.ListStatesResponse], error)
	// GetStateConfig retrieves backend configuration for an existing state by logic ID.
	GetStateConfig(context.Context, *connect.Request[v1.GetStateConfigRequest]) (*connect.Response[v1.GetStateConfigResponse], error)
	// GetStateLock inspects the current lock metadata for a state by GUID.
	GetStateLock(context.Context, *connect.Request[v1.GetStateLockRequest]) (*connect.Response[v1.GetStateLockResponse], error)
	// UnlockState releases a lock using the lock ID provided by Terraform/OpenTofu.
	UnlockState(context.Context, *connect.Request[v1.UnlockStateRequest]) (*connect.Response[v1.UnlockStateResponse], error)
	// AddDependency declares a dependency edge from producer output to consumer state.
	// Returns existing edge if duplicate (idempotent). Rejects if would create cycle.
	AddDependency(context.Context, *connect.Request[v1.AddDependencyRequest]) (*connect.Response[v1.AddDependencyResponse], error)
	// RemoveDependency deletes a dependency edge by ID.
	RemoveDependency(context.Context, *connect.Request[v1.RemoveDependencyRequest]) (*connect.Response[v1.RemoveDependencyResponse], error)
	// ListDependencies returns all edges where the given state is the consumer (incoming deps).
	ListDependencies(context.Context, *connect.Request[v1.ListDependenciesRequest]) (*connect.Response[v1.ListDependenciesResponse], error)
	// ListDependents returns all edges where the given state is the producer (outgoing deps).
	ListDependents(context.Context, *connect.Request[v1.ListDependentsRequest]) (*connect.Response[v1.ListDependentsResponse], error)
	// SearchByOutput finds all edges that reference a specific output key (by name).
	SearchByOutput(context.Context, *connect.Request[v1.SearchByOutputRequest]) (*connect.Response[v1.SearchByOutputResponse], error)
	// GetTopologicalOrder computes layered ordering of states rooted at given state.
	GetTopologicalOrder(context.Context, *connect.Request[v1.GetTopologicalOrderRequest]) (*connect.Response[v1.GetTopologicalOrderResponse], error)
	// GetStateStatus computes on-demand status for a state based on its incoming edges.
	GetStateStatus(context.Context, *connect.Request[v1.GetStateStatusRequest]) (*connect.Response[v1.GetStateStatusResponse], error)
	// GetDependencyGraph returns full dependency graph data for client-side HCL generation.
	GetDependencyGraph(context.Context, *connect.Request[v1.GetDependencyGraphRequest]) (*connect.Response[v1.GetDependencyGraphResponse], error)
	// ListStateOutputs returns available output keys from a state's Terraform/OpenTofu JSON.
	// Output values are NOT returned (security/size concerns); only keys and sensitive flags.
	// Used by CLI for interactive output selection when creating dependencies.
	ListStateOutputs(context.Context, *connect.Request[v1.ListStateOutputsRequest]) (*connect.Response[v1.ListStateOutputsResponse], error)
	// GetStateInfo retrieves comprehensive state information including:
	// - Basic metadata (GUID, logic-id, timestamps)
	// - Backend configuration (Terraform HTTP backend URLs)
	// - Dependencies (incoming edges: states this state depends on)
	// - Dependents (outgoing edges: states that depend on this state)
	// - Outputs (available Terraform output keys from state JSON)
	//
	// This consolidates information previously requiring multiple RPC calls.
	GetStateInfo(context.Context, *connect.Request[v1.GetStateInfoRequest]) (*connect.Response[v1.GetStateInfoResponse], error)
}

// NewStateServiceClient constructs a client for the state.v1.StateService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewStateServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) StateServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	stateServiceMethods := v1.File_state_v1_state_proto.Services().ByName("StateService").Methods()
	return &stateServiceClient{
		createState: connect.NewClient[v1.CreateStateRequest, v1.CreateStateResponse](
			httpClient,
			baseURL+StateServiceCreateStateProcedure,
			connect.WithSchema(stateServiceMethods.ByName("CreateState")),
			connect.WithClientOptions(opts...),
		),
		listStates: connect.NewClient[v1.ListStatesRequest, v1.ListStatesResponse](
			httpClient,
			baseURL+StateServiceListStatesProcedure,
			connect.WithSchema(stateServiceMethods.ByName("ListStates")),
			connect.WithClientOptions(opts...),
		),
		getStateConfig: connect.NewClient[v1.GetStateConfigRequest, v1.GetStateConfigResponse](
			httpClient,
			baseURL+StateServiceGetStateConfigProcedure,
			connect.WithSchema(stateServiceMethods.ByName("GetStateConfig")),
			connect.WithClientOptions(opts...),
		),
		getStateLock: connect.NewClient[v1.GetStateLockRequest, v1.GetStateLockResponse](
			httpClient,
			baseURL+StateServiceGetStateLockProcedure,
			connect.WithSchema(stateServiceMethods.ByName("GetStateLock")),
			connect.WithClientOptions(opts...),
		),
		unlockState: connect.NewClient[v1.UnlockStateRequest, v1.UnlockStateResponse](
			httpClient,
			baseURL+StateServiceUnlockStateProcedure,
			connect.WithSchema(stateServiceMethods.ByName("UnlockState")),
			connect.WithClientOptions(opts...),
		),
		addDependency: connect.NewClient[v1.AddDependencyRequest, v1.AddDependencyResponse](
			httpClient,
			baseURL+StateServiceAddDependencyProcedure,
			connect.WithSchema(stateServiceMethods.ByName("AddDependency")),
			connect.WithClientOptions(opts...),
		),
		removeDependency: connect.NewClient[v1.RemoveDependencyRequest, v1.RemoveDependencyResponse](
			httpClient,
			baseURL+StateServiceRemoveDependencyProcedure,
			connect.WithSchema(stateServiceMethods.ByName("RemoveDependency")),
			connect.WithClientOptions(opts...),
		),
		listDependencies: connect.NewClient[v1.ListDependenciesRequest, v1.ListDependenciesResponse](
			httpClient,
			baseURL+StateServiceListDependenciesProcedure,
			connect.WithSchema(stateServiceMethods.ByName("ListDependencies")),
			connect.WithClientOptions(opts...),
		),
		listDependents: connect.NewClient[v1.ListDependentsRequest, v1.ListDependentsResponse](
			httpClient,
			baseURL+StateServiceListDependentsProcedure,
			connect.WithSchema(stateServiceMethods.ByName("ListDependents")),
			connect.WithClientOptions(opts...),
		),
		searchByOutput: connect.NewClient[v1.SearchByOutputRequest, v1.SearchByOutputResponse](
			httpClient,
			baseURL+StateServiceSearchByOutputProcedure,
			connect.WithSchema(stateServiceMethods.ByName("SearchByOutput")),
			connect.WithClientOptions(opts...),
		),
		getTopologicalOrder: connect.NewClient[v1.GetTopologicalOrderRequest, v1.GetTopologicalOrderResponse](
			httpClient,
			baseURL+StateServiceGetTopologicalOrderProcedure,
			connect.WithSchema(stateServiceMethods.ByName("GetTopologicalOrder")),
			connect.WithClientOptions(opts...),
		),
		getStateStatus: connect.NewClient[v1.GetStateStatusRequest, v1.GetStateStatusResponse](
			httpClient,
			baseURL+StateServiceGetStateStatusProcedure,
			connect.WithSchema(stateServiceMethods.ByName("GetStateStatus")),
			connect.WithClientOptions(opts...),
		),
		getDependencyGraph: connect.NewClient[v1.GetDependencyGraphRequest, v1.GetDependencyGraphResponse](
			httpClient,
			baseURL+StateServiceGetDependencyGraphProcedure,
			connect.WithSchema(stateServiceMethods.ByName("GetDependencyGraph")),
			connect.WithClientOptions(opts...),
		),
		listStateOutputs: connect.NewClient[v1.ListStateOutputsRequest, v1.ListStateOutputsResponse](
			httpClient,
			baseURL+StateServiceListStateOutputsProcedure,
			connect.WithSchema(stateServiceMethods.ByName("ListStateOutputs")),
			connect.WithClientOptions(opts...),
		),
		getStateInfo: connect.NewClient[v1.GetStateInfoRequest, v1.GetStateInfoResponse](
			httpClient,
			baseURL+StateServiceGetStateInfoProcedure,
			connect.WithSchema(stateServiceMethods.ByName("GetStateInfo")),
			connect.WithClientOptions(opts...),
		),
	}
}

// stateServiceClient implements StateServiceClient.
type stateServiceClient struct {
	createState         *connect.Client[v1.CreateStateRequest, v1.CreateStateResponse]
	listStates          *connect.Client[v1.ListStatesRequest, v1.ListStatesResponse]
	getStateConfig      *connect.Client[v1.GetStateConfigRequest, v1.GetStateConfigResponse]
	getStateLock        *connect.Client[v1.GetStateLockRequest, v1.GetStateLockResponse]
	unlockState         *connect.Client[v1.UnlockStateRequest, v1.UnlockStateResponse]
	addDependency       *connect.Client[v1.AddDependencyRequest, v1.AddDependencyResponse]
	removeDependency    *connect.Client[v1.RemoveDependencyRequest, v1.RemoveDependencyResponse]
	listDependencies    *connect.Client[v1.ListDependenciesRequest, v1.ListDependenciesResponse]
	listDependents      *connect.Client[v1.ListDependentsRequest, v1.ListDependentsResponse]
	searchByOutput      *connect.Client[v1.SearchByOutputRequest, v1.SearchByOutputResponse]
	getTopologicalOrder *connect.Client[v1.GetTopologicalOrderRequest, v1.GetTopologicalOrderResponse]
	getStateStatus      *connect.Client[v1.GetStateStatusRequest, v1.GetStateStatusResponse]
	getDependencyGraph  *connect.Client[v1.GetDependencyGraphRequest, v1.GetDependencyGraphResponse]
	listStateOutputs    *connect.Client[v1.ListStateOutputsRequest, v1.ListStateOutputsResponse]
	getStateInfo        *connect.Client[v1.GetStateInfoRequest, v1.GetStateInfoResponse]
}

// CreateState calls state.v1.StateService.CreateState.
func (c *stateServiceClient) CreateState(ctx context.Context, req *connect.Request[v1.CreateStateRequest]) (*connect.Response[v1.CreateStateResponse], error) {
	return c.createState.CallUnary(ctx, req)
}

// ListStates calls state.v1.StateService.ListStates.
func (c *stateServiceClient) ListStates(ctx context.Context, req *connect.Request[v1.ListStatesRequest]) (*connect.Response[v1.ListStatesResponse], error) {
	return c.listStates.CallUnary(ctx, req)
}

// GetStateConfig calls state.v1.StateService.GetStateConfig.
func (c *stateServiceClient) GetStateConfig(ctx context.Context, req *connect.Request[v1.GetStateConfigRequest]) (*connect.Response[v1.GetStateConfigResponse], error) {
	return c.getStateConfig.CallUnary(ctx, req)
}

// GetStateLock calls state.v1.StateService.GetStateLock.
func (c *stateServiceClient) GetStateLock(ctx context.Context, req *connect.Request[v1.GetStateLockRequest]) (*connect.Response[v1.GetStateLockResponse], error) {
	return c.getStateLock.CallUnary(ctx, req)
}

// UnlockState calls state.v1.StateService.UnlockState.
func (c *stateServiceClient) UnlockState(ctx context.Context, req *connect.Request[v1.UnlockStateRequest]) (*connect.Response[v1.UnlockStateResponse], error) {
	return c.unlockState.CallUnary(ctx, req)
}

// AddDependency calls state.v1.StateService.AddDependency.
func (c *stateServiceClient) AddDependency(ctx context.Context, req *connect.Request[v1.AddDependencyRequest]) (*connect.Response[v1.AddDependencyResponse], error) {
	return c.addDependency.CallUnary(ctx, req)
}

// RemoveDependency calls state.v1.StateService.RemoveDependency.
func (c *stateServiceClient) RemoveDependency(ctx context.Context, req *connect.Request[v1.RemoveDependencyRequest]) (*connect.Response[v1.RemoveDependencyResponse], error) {
	return c.removeDependency.CallUnary(ctx, req)
}

// ListDependencies calls state.v1.StateService.ListDependencies.
func (c *stateServiceClient) ListDependencies(ctx context.Context, req *connect.Request[v1.ListDependenciesRequest]) (*connect.Response[v1.ListDependenciesResponse], error) {
	return c.listDependencies.CallUnary(ctx, req)
}

// ListDependents calls state.v1.StateService.ListDependents.
func (c *stateServiceClient) ListDependents(ctx context.Context, req *connect.Request[v1.ListDependentsRequest]) (*connect.Response[v1.ListDependentsResponse], error) {
	return c.listDependents.CallUnary(ctx, req)
}

// SearchByOutput calls state.v1.StateService.SearchByOutput.
func (c *stateServiceClient) SearchByOutput(ctx context.Context, req *connect.Request[v1.SearchByOutputRequest]) (*connect.Response[v1.SearchByOutputResponse], error) {
	return c.searchByOutput.CallUnary(ctx, req)
}

// GetTopologicalOrder calls state.v1.StateService.GetTopologicalOrder.
func (c *stateServiceClient) GetTopologicalOrder(ctx context.Context, req *connect.Request[v1.GetTopologicalOrderRequest]) (*connect.Response[v1.GetTopologicalOrderResponse], error) {
	return c.getTopologicalOrder.CallUnary(ctx, req)
}

// GetStateStatus calls state.v1.StateService.GetStateStatus.
func (c *stateServiceClient) GetStateStatus(ctx context.Context, req *connect.Request[v1.GetStateStatusRequest]) (*connect.Response[v1.GetStateStatusResponse], error) {
	return c.getStateStatus.CallUnary(ctx, req)
}

// GetDependencyGraph calls state.v1.StateService.GetDependencyGraph.
func (c *stateServiceClient) GetDependencyGraph(ctx context.Context, req *connect.Request[v1.GetDependencyGraphRequest]) (*connect.Response[v1.GetDependencyGraphResponse], error) {
	return c.getDependencyGraph.CallUnary(ctx, req)
}

// ListStateOutputs calls state.v1.StateService.ListStateOutputs.
func (c *stateServiceClient) ListStateOutputs(ctx context.Context, req *connect.Request[v1.ListStateOutputsRequest]) (*connect.Response[v1.ListStateOutputsResponse], error) {
	return c.listStateOutputs.CallUnary(ctx, req)
}

// GetStateInfo calls state.v1.StateService.GetStateInfo.
func (c *stateServiceClient) GetStateInfo(ctx context.Context, req *connect.Request[v1.GetStateInfoRequest]) (*connect.Response[v1.GetStateInfoResponse], error) {
	return c.getStateInfo.CallUnary(ctx, req)
}

// StateServiceHandler is an implementation of the state.v1.StateService service.
type StateServiceHandler interface {
	// CreateState creates a new state with client-generated GUID and logic ID.
	CreateState(context.Context, *connect.Request[v1.CreateStateRequest]) (*connect.Response[v1.CreateStateResponse], error)
	// ListStates returns all states with summary information.
	ListStates(context.Context, *connect.Request[v1.ListStatesRequest]) (*connect.Response[v1.ListStatesResponse], error)
	// GetStateConfig retrieves backend configuration for an existing state by logic ID.
	GetStateConfig(context.Context, *connect.Request[v1.GetStateConfigRequest]) (*connect.Response[v1.GetStateConfigResponse], error)
	// GetStateLock inspects the current lock metadata for a state by GUID.
	GetStateLock(context.Context, *connect.Request[v1.GetStateLockRequest]) (*connect.Response[v1.GetStateLockResponse], error)
	// UnlockState releases a lock using the lock ID provided by Terraform/OpenTofu.
	UnlockState(context.Context, *connect.Request[v1.UnlockStateRequest]) (*connect.Response[v1.UnlockStateResponse], error)
	// AddDependency declares a dependency edge from producer output to consumer state.
	// Returns existing edge if duplicate (idempotent). Rejects if would create cycle.
	AddDependency(context.Context, *connect.Request[v1.AddDependencyRequest]) (*connect.Response[v1.AddDependencyResponse], error)
	// RemoveDependency deletes a dependency edge by ID.
	RemoveDependency(context.Context, *connect.Request[v1.RemoveDependencyRequest]) (*connect.Response[v1.RemoveDependencyResponse], error)
	// ListDependencies returns all edges where the given state is the consumer (incoming deps).
	ListDependencies(context.Context, *connect.Request[v1.ListDependenciesRequest]) (*connect.Response[v1.ListDependenciesResponse], error)
	// ListDependents returns all edges where the given state is the producer (outgoing deps).
	ListDependents(context.Context, *connect.Request[v1.ListDependentsRequest]) (*connect.Response[v1.ListDependentsResponse], error)
	// SearchByOutput finds all edges that reference a specific output key (by name).
	SearchByOutput(context.Context, *connect.Request[v1.SearchByOutputRequest]) (*connect.Response[v1.SearchByOutputResponse], error)
	// GetTopologicalOrder computes layered ordering of states rooted at given state.
	GetTopologicalOrder(context.Context, *connect.Request[v1.GetTopologicalOrderRequest]) (*connect.Response[v1.GetTopologicalOrderResponse], error)
	// GetStateStatus computes on-demand status for a state based on its incoming edges.
	GetStateStatus(context.Context, *connect.Request[v1.GetStateStatusRequest]) (*connect.Response[v1.GetStateStatusResponse], error)
	// GetDependencyGraph returns full dependency graph data for client-side HCL generation.
	GetDependencyGraph(context.Context, *connect.Request[v1.GetDependencyGraphRequest]) (*connect.Response[v1.GetDependencyGraphResponse], error)
	// ListStateOutputs returns available output keys from a state's Terraform/OpenTofu JSON.
	// Output values are NOT returned (security/size concerns); only keys and sensitive flags.
	// Used by CLI for interactive output selection when creating dependencies.
	ListStateOutputs(context.Context, *connect.Request[v1.ListStateOutputsRequest]) (*connect.Response[v1.ListStateOutputsResponse], error)
	// GetStateInfo retrieves comprehensive state information including:
	// - Basic metadata (GUID, logic-id, timestamps)
	// - Backend configuration (Terraform HTTP backend URLs)
	// - Dependencies (incoming edges: states this state depends on)
	// - Dependents (outgoing edges: states that depend on this state)
	// - Outputs (available Terraform output keys from state JSON)
	//
	// This consolidates information previously requiring multiple RPC calls.
	GetStateInfo(context.Context, *connect.Request[v1.GetStateInfoRequest]) (*connect.Response[v1.GetStateInfoResponse], error)
}

// NewStateServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewStateServiceHandler(svc StateServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	stateServiceMethods := v1.File_state_v1_state_proto.Services().ByName("StateService").Methods()
	stateServiceCreateStateHandler := connect.NewUnaryHandler(
		StateServiceCreateStateProcedure,
		svc.CreateState,
		connect.WithSchema(stateServiceMethods.ByName("CreateState")),
		connect.WithHandlerOptions(opts...),
	)
	stateServiceListStatesHandler := connect.NewUnaryHandler(
		StateServiceListStatesProcedure,
		svc.ListStates,
		connect.WithSchema(stateServiceMethods.ByName("ListStates")),
		connect.WithHandlerOptions(opts...),
	)
	stateServiceGetStateConfigHandler := connect.NewUnaryHandler(
		StateServiceGetStateConfigProcedure,
		svc.GetStateConfig,
		connect.WithSchema(stateServiceMethods.ByName("GetStateConfig")),
		connect.WithHandlerOptions(opts...),
	)
	stateServiceGetStateLockHandler := connect.NewUnaryHandler(
		StateServiceGetStateLockProcedure,
		svc.GetStateLock,
		connect.WithSchema(stateServiceMethods.ByName("GetStateLock")),
		connect.WithHandlerOptions(opts...),
	)
	stateServiceUnlockStateHandler := connect.NewUnaryHandler(
		StateServiceUnlockStateProcedure,
		svc.UnlockState,
		connect.WithSchema(stateServiceMethods.ByName("UnlockState")),
		connect.WithHandlerOptions(opts...),
	)
	stateServiceAddDependencyHandler := connect.NewUnaryHandler(
		StateServiceAddDependencyProcedure,
		svc.AddDependency,
		connect.WithSchema(stateServiceMethods.ByName("AddDependency")),
		connect.WithHandlerOptions(opts...),
	)
	stateServiceRemoveDependencyHandler := connect.NewUnaryHandler(
		StateServiceRemoveDependencyProcedure,
		svc.RemoveDependency,
		connect.WithSchema(stateServiceMethods.ByName("RemoveDependency")),
		connect.WithHandlerOptions(opts...),
	)
	stateServiceListDependenciesHandler := connect.NewUnaryHandler(
		StateServiceListDependenciesProcedure,
		svc.ListDependencies,
		connect.WithSchema(stateServiceMethods.ByName("ListDependencies")),
		connect.WithHandlerOptions(opts...),
	)
	stateServiceListDependentsHandler := connect.NewUnaryHandler(
		StateServiceListDependentsProcedure,
		svc.ListDependents,
		connect.WithSchema(stateServiceMethods.ByName("ListDependents")),
		connect.WithHandlerOptions(opts...),
	)
	stateServiceSearchByOutputHandler := connect.NewUnaryHandler(
		StateServiceSearchByOutputProcedure,
		svc.SearchByOutput,
		connect.WithSchema(stateServiceMethods.ByName("SearchByOutput")),
		connect.WithHandlerOptions(opts...),
	)
	stateServiceGetTopologicalOrderHandler := connect.NewUnaryHandler(
		StateServiceGetTopologicalOrderProcedure,
		svc.GetTopologicalOrder,
		connect.WithSchema(stateServiceMethods.ByName("GetTopologicalOrder")),
		connect.WithHandlerOptions(opts...),
	)
	stateServiceGetStateStatusHandler := connect.NewUnaryHandler(
		StateServiceGetStateStatusProcedure,
		svc.GetStateStatus,
		connect.WithSchema(stateServiceMethods.ByName("GetStateStatus")),
		connect.WithHandlerOptions(opts...),
	)
	stateServiceGetDependencyGraphHandler := connect.NewUnaryHandler(
		StateServiceGetDependencyGraphProcedure,
		svc.GetDependencyGraph,
		connect.WithSchema(stateServiceMethods.ByName("GetDependencyGraph")),
		connect.WithHandlerOptions(opts...),
	)
	stateServiceListStateOutputsHandler := connect.NewUnaryHandler(
		StateServiceListStateOutputsProcedure,
		svc.ListStateOutputs,
		connect.WithSchema(stateServiceMethods.ByName("ListStateOutputs")),
		connect.WithHandlerOptions(opts...),
	)
	stateServiceGetStateInfoHandler := connect.NewUnaryHandler(
		StateServiceGetStateInfoProcedure,
		svc.GetStateInfo,
		connect.WithSchema(stateServiceMethods.ByName("GetStateInfo")),
		connect.WithHandlerOptions(opts...),
	)
	return "/state.v1.StateService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case StateServiceCreateStateProcedure:
			stateServiceCreateStateHandler.ServeHTTP(w, r)
		case StateServiceListStatesProcedure:
			stateServiceListStatesHandler.ServeHTTP(w, r)
		case StateServiceGetStateConfigProcedure:
			stateServiceGetStateConfigHandler.ServeHTTP(w, r)
		case StateServiceGetStateLockProcedure:
			stateServiceGetStateLockHandler.ServeHTTP(w, r)
		case StateServiceUnlockStateProcedure:
			stateServiceUnlockStateHandler.ServeHTTP(w, r)
		case StateServiceAddDependencyProcedure:
			stateServiceAddDependencyHandler.ServeHTTP(w, r)
		case StateServiceRemoveDependencyProcedure:
			stateServiceRemoveDependencyHandler.ServeHTTP(w, r)
		case StateServiceListDependenciesProcedure:
			stateServiceListDependenciesHandler.ServeHTTP(w, r)
		case StateServiceListDependentsProcedure:
			stateServiceListDependentsHandler.ServeHTTP(w, r)
		case StateServiceSearchByOutputProcedure:
			stateServiceSearchByOutputHandler.ServeHTTP(w, r)
		case StateServiceGetTopologicalOrderProcedure:
			stateServiceGetTopologicalOrderHandler.ServeHTTP(w, r)
		case StateServiceGetStateStatusProcedure:
			stateServiceGetStateStatusHandler.ServeHTTP(w, r)
		case StateServiceGetDependencyGraphProcedure:
			stateServiceGetDependencyGraphHandler.ServeHTTP(w, r)
		case StateServiceListStateOutputsProcedure:
			stateServiceListStateOutputsHandler.ServeHTTP(w, r)
		case StateServiceGetStateInfoProcedure:
			stateServiceGetStateInfoHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedStateServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedStateServiceHandler struct{}

func (UnimplementedStateServiceHandler) CreateState(context.Context, *connect.Request[v1.CreateStateRequest]) (*connect.Response[v1.CreateStateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("state.v1.StateService.CreateState is not implemented"))
}

func (UnimplementedStateServiceHandler) ListStates(context.Context, *connect.Request[v1.ListStatesRequest]) (*connect.Response[v1.ListStatesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("state.v1.StateService.ListStates is not implemented"))
}

func (UnimplementedStateServiceHandler) GetStateConfig(context.Context, *connect.Request[v1.GetStateConfigRequest]) (*connect.Response[v1.GetStateConfigResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("state.v1.StateService.GetStateConfig is not implemented"))
}

func (UnimplementedStateServiceHandler) GetStateLock(context.Context, *connect.Request[v1.GetStateLockRequest]) (*connect.Response[v1.GetStateLockResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("state.v1.StateService.GetStateLock is not implemented"))
}

func (UnimplementedStateServiceHandler) UnlockState(context.Context, *connect.Request[v1.UnlockStateRequest]) (*connect.Response[v1.UnlockStateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("state.v1.StateService.UnlockState is not implemented"))
}

func (UnimplementedStateServiceHandler) AddDependency(context.Context, *connect.Request[v1.AddDependencyRequest]) (*connect.Response[v1.AddDependencyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("state.v1.StateService.AddDependency is not implemented"))
}

func (UnimplementedStateServiceHandler) RemoveDependency(context.Context, *connect.Request[v1.RemoveDependencyRequest]) (*connect.Response[v1.RemoveDependencyResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("state.v1.StateService.RemoveDependency is not implemented"))
}

func (UnimplementedStateServiceHandler) ListDependencies(context.Context, *connect.Request[v1.ListDependenciesRequest]) (*connect.Response[v1.ListDependenciesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("state.v1.StateService.ListDependencies is not implemented"))
}

func (UnimplementedStateServiceHandler) ListDependents(context.Context, *connect.Request[v1.ListDependentsRequest]) (*connect.Response[v1.ListDependentsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("state.v1.StateService.ListDependents is not implemented"))
}

func (UnimplementedStateServiceHandler) SearchByOutput(context.Context, *connect.Request[v1.SearchByOutputRequest]) (*connect.Response[v1.SearchByOutputResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("state.v1.StateService.SearchByOutput is not implemented"))
}

func (UnimplementedStateServiceHandler) GetTopologicalOrder(context.Context, *connect.Request[v1.GetTopologicalOrderRequest]) (*connect.Response[v1.GetTopologicalOrderResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("state.v1.StateService.GetTopologicalOrder is not implemented"))
}

func (UnimplementedStateServiceHandler) GetStateStatus(context.Context, *connect.Request[v1.GetStateStatusRequest]) (*connect.Response[v1.GetStateStatusResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("state.v1.StateService.GetStateStatus is not implemented"))
}

func (UnimplementedStateServiceHandler) GetDependencyGraph(context.Context, *connect.Request[v1.GetDependencyGraphRequest]) (*connect.Response[v1.GetDependencyGraphResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("state.v1.StateService.GetDependencyGraph is not implemented"))
}

func (UnimplementedStateServiceHandler) ListStateOutputs(context.Context, *connect.Request[v1.ListStateOutputsRequest]) (*connect.Response[v1.ListStateOutputsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("state.v1.StateService.ListStateOutputs is not implemented"))
}

func (UnimplementedStateServiceHandler) GetStateInfo(context.Context, *connect.Request[v1.GetStateInfoRequest]) (*connect.Response[v1.GetStateInfoResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("state.v1.StateService.GetStateInfo is not implemented"))
}
